Image.list info update
apptainer/singularity pull request #1190
Opened 2017-12-01 14:41 UTC by ArangoGutierrez

**Description of the Pull Request (PR):**

In order to align the current info print from instance.list
Replaced:
```bash  
  $ singularity instance.list
    /home/mibauer/singularity/sinstance/test.img  [2056.132716]  Instances:
         Instance PID:   11963
         Instance Name:  test
         
    $ sudo singularity instance.list -u mibauer
    /home/mibauer/singularity/sinstance/test.img  [2056.132716]  Instances:
         Instance PID:   16219
         Instance Name:  test
         
         Instance PID:   11963
         Instance Name:  test
```

For:

```bash
    $ singularity instance.list
    DAEMON NAME      PID      CONTAINER IMAGE
    test            11963     /home/mibauer/singularity/sinstance/test.img
         
    $ sudo singularity instance.list -u mibauer
        DAEMON NAME      PID      CONTAINER IMAGE
    test            11963     /home/mibauer/singularity/sinstance/test.img
    test            16219     /home/mibauer/singularity/sinstance/test.img
```

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

2017-12-05 21:03 UTC, GodloveD requested changes
Thanks very much for looking through the help docs and working to keep us honest.  It's much appreciated.  I think there are still a few changes that need to be made to work this in.

2017-12-05 21:03 UTC, GodloveD commented on libexec/cli/instance.list.info
> +        DAEMON NAME      PID      CONTAINER IMAGE
I think a stray tab must have snuck into this line.

2017-12-05 21:03 UTC, GodloveD commented on libexec/cli/instance.list.info
> +    test            16219     /home/mibauer/singularity/sinstance/test.img
This still doesn't seem completely realistic.  I don't think two instances can share the same name.  I think the second line should read something like:
```
test2           16219     /home/mibauer/singularity/sinstance/test.img
```

2017-12-05 21:12 UTC, ArangoGutierrez commented
Changes proposed by @GodloveD on commit #b628c1d

2017-12-05 21:30 UTC, GodloveD approved these changes
Looks good to me!

2018-01-02 17:40 UTC, GodloveD commented
@bauerm97 can you please review this very small change to the documentation and let me know if it looks good to you?  If it does I will merge.  Thank you.

2018-01-02 21:09 UTC, bauerm97 commented
@GodloveD looks good to me!

2018-01-02 21:13 UTC, merged

2018-01-02 21:13 UTC, GodloveD commented
Thanks @ArangoGutierrez !