Add check for mksquashfs binary to configure.ac
apptainer/singularity pull request #1246
Opened 2018-01-09 21:37 UTC by jmstover

**Description of the Pull Request (PR):**

mksquashfs is a hard requirement in the .spec file. Have the configure script fail if the mksquashfs binary isn't found, making it a hard requirement building from source as well.

**Checkoff for all PRs:**

- [X ] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ X] I have tested this PR locally with a `make test`
- [ X] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [ X] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-01-12 16:53 UTC, olifre commented
It seems this still shows an error, e.g.:
```
rm ./.deps
rm: cannot remove './.deps': Is a directory
Makefile:955: recipe for target 'distclean' failed
make[4]: [distclean] Error 1 (ignored)
```
See:
https://travis-ci.org/olifre/singularity/jobs/328191995
for details.

2018-01-12 17:00 UTC, olifre commented
In addition, it seems to be incomplete. 
See:
https://travis-ci.org/olifre/singularity/jobs/328194283
which contains at the end:
```
dpkg-source: error: cannot represent change to libexec/python/defaults.pyc: binary file contents changed
dpkg-source: error: add libexec/python/defaults.pyc in debian/source/include-binaries if you want to store the modified binary in the debian tarball
dpkg-source: error: cannot represent change to libexec/python/message.pyc: binary file contents changed
dpkg-source: error: add libexec/python/message.pyc in debian/source/include-binaries if you want to store the modified binary in the debian tarball
dpkg-source: error: cannot represent change to libexec/python/sutils.pyc: binary file contents changed
dpkg-source: error: add libexec/python/sutils.pyc in debian/source/include-binaries if you want to store the modified binary in the debian tarball
dpkg-source: warning: executable mode 0755 of 'missing' will not be represented in diff
dpkg-source: error: cannot represent change to src/lib/signing/libsigning_la-crypt.o: binary file contents changed
dpkg-source: error: add src/lib/signing/libsigning_la-crypt.o in debian/source/include-binaries if you want to store the modified binary in the debian tarball
dpkg-source: error: unrepresentable changes to source
```
This is Debian packaging diffing the original source tarball and the files found after `make distclean`.

2018-01-12 17:11 UTC, jmstover commented
Grab at least `c34dfb5`. I noticed after the fact that the initial rm's didn't have a `-rf` when trying to remove a directory (though it didn't error for me :/ ). That last commit, should fix that, and catch the `.libs` directory as well.

And I'm not sure on the Python side... I guess I can add in a `rm -f *.pyc` and just be done with it.

2018-01-12 17:31 UTC, olifre commented
> That last commit, should fix that, and catch the .libs directory as well.

Yes, that's why I also cherry-picked it. However, it misses the directory I cited and you can find in the build log I mentioned. 
This is the place:
`src/lib/image/Makefile.am` which still misses the `-rf` for `.deps`. 


> And I'm not sure on the Python side... I guess I can add in a rm -f *.pyc and just be done with it.

That should fix it. The remaining object file seems to be missing distcleaning in:
`src/lib/signing/Makefile.am`.

2018-01-12 17:51 UTC, jmstover commented
@olifre Working on getting it cleaned up now.... Hopefully this next commit will straighten it out

2018-01-12 19:07 UTC, olifre commented
Nice improvement!
It seems now the `Makefile.in` files are left:
https://travis-ci.org/olifre/singularity/jobs/328233225
They are in `.gitignore`, but still I'd expect they are removed by `distclean` (and it seems Debian expects that, too).

2018-01-12 19:10 UTC, olifre commented
> They are in .gitignore, but still I'd expect they are removed by distclean (and it seems Debian expects that, too).

Or maybe they should not, since they are created by `autogen` and not `make`? I'm not sure, what is the general approach?

2018-01-12 19:55 UTC, olifre commented
Mhhhm. Running:
`make distclean && git clean -fx` appears to do the job fine. 

However, going with the definition of `distclean` from https://www.gnu.org/prep/standards/html_node/Standard-Targets.html , I would say `make distclean` alone should restore the exact state of `git archive` (or an archive downloaded from github releases). 
This would mean it should also cleanup the stuff created by autogen and configure, even though it's gitignored.

2018-01-12 20:46 UTC, jmstover commented
I just downloaded the release 2.4.2 tarball from GitHub and it has the Makefile.in files in it.  In theory, that's correct. A release should *not* have the `*.ac` or `*.am` files... as that's a maintainer thing. But GMK usually ships everything to rebuild from the original sources if wanted.

The Makefile.in files are used to build the corresponding Makefile when the configure script is ran. If you look in `configure.ac` in the `AC_CONFIG_FILE` section, those file get built from corresponding `[name].in` file. So... `make maintainer-clean` should remove the `*.in` files, but not `distclean`.

2018-01-13 03:42 UTC, olifre commented
> I just downloaded the release 2.4.2 tarball from GitHub and it has the Makefile.in files in it. In theory, that's correct. A release should not have the *.ac or *.am files... as that's a maintainer thing. But GMK usually ships everything to rebuild from the original sources if wanted.

Thanks for pointing this out! Yes, indeed I was unaware that e.g. https://github.com/singularityware/singularity/releases/download/2.4.2/singularity-2.4.2.tar.gz and https://github.com/singularityware/singularity/archive/2.4.2.tar.gz (or a "git archive") have different contents. Hence, I would not call the "release tarball" the "original source". Also, this means that building from the source tree and from a release tarball may yield different results, especially if the person building the package uses a different automake version than GMK. 
Maybe I'll open another issue asking for documentation of what exactly has been done between the sources and the release tarball (probably just autoreconf, but that should be documented, and also the automake version used) since it's not part of the release checklist. 



> So... make maintainer-clean should remove some of the *.in files, but not distclean.

Thanks, that explains it. Still, running `make maintainer-clean` forgets two files:
```
compile
man/Makefile.in
```
Should I open a separate issue on that?

2018-01-13 04:27 UTC, jmstover commented
> Still, running make maintainer-clean forgets two files

Thanks, I'll get those add in and push another update. Trying to get as much as possible cleaned up in the Makefiles from this one PR.

2018-01-13 04:33 UTC, olifre commented
Thanks! I'll adapt my packaging tests tomorrow and let you know if anything else pops up, but I think this should be complete. :smile:

2018-01-13 05:51 UTC, jmstover commented
> Maybe I'll open another issue asking for documentation of what exactly has 
> been done between the sources and the release tarball (probably just autoreconf

Looking at it, the releases tarballs are probably created by running something like:

`./autogen.sh && ./configure && make dist-gzip`

That creates a `singularity-[version].tar.gz` file.

The Makefiles don't really specify anything for the dist_* variables, so `make dist` pretty much just takes the structure. That includes the `Makefile.am` files, and everything else. If you want to control what gets caught up, you have to specify every file that's either included or excluded in it.

2018-01-16 21:13 UTC, GodloveD requested changes
Hey @jmstover.  I tested this and it looks like it works from what I can tell.  Let me just suggest a single change to the error message.

2018-01-16 21:13 UTC, GodloveD commented on configure.ac
> +    AC_MSG_ERROR([mksquashfs is required.])
Would you mind making this warning more like the other warnings in `configure.ac`.  How about this:
```
configure: error: Unable to find mksquashfs, need package squashfs-tools
```
That way a user who doesn't really know how to fix this error doesn't have to Google it.

2018-01-16 21:41 UTC, jmstover commented
@GodloveD Output message updated.

2018-01-17 02:46 UTC, GodloveD approved these changes

2018-01-17 02:49 UTC, GodloveD commented
Groovy.  Don't know why the Travis build isn't running.  I tried stopping and restarting but to no avail.  I'll try again in the morning.  If it passes I'll go ahead and merge.

2018-01-17 02:51 UTC, olifre commented
> Groovy. Don't know why the Travis build isn't running. I tried stopping and restarting but to no avail. I'll try again in the morning. If it passes I'll go ahead and merge.

Travis is currently dead:
https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

2018-01-17 02:52 UTC, olifre commented
The following valid point has been raised in #1204 by @c-ney : Why is `mksquashfs` required to _build_ singularity? 
The RPM only requires it as a `Requires`, i.e. only for installation of the final package. 
Is it really used at build time for anything? If not, this check should surely not go in, if yes, this PR should also adapt the spec file to make it a `BuildRequires`.,

2018-01-17 02:56 UTC, vsoch commented
RIP Travis 😢

2018-01-17 05:41 UTC, jmstover commented
@olifre Yes, it's a Require in the RPM spec file, so would be added when the RPM is installed.

But building from source we can't force something being there as you can with a package that tracks dependencies. So, since it's used we say it needs to be there when built since we can check that.

This is where it's different between a SPEC file and the source. The SPEC file is going to force the install when the package is installed, but there's no way building from source we can do the same thing unless we bail out if we don't find it during the `./configure` stage.

The initial reason it came up is because someone was building from source and had questions on mksquashfs and where it was required (they initially didn't have it anywhere). So, this is as close to being an equivalent "Require" with autoconf as we can get.

2018-01-17 07:21 UTC, jmstover commented
Okay... it may be possible to change this to just output this information. So, something like this in the top-level `Makefile.am`;

```
all-local:
    @echo
    @echo "****   mksquashfs from squashfs-tools is required to run Singularity ****"
    @echo
```

But, there's no guarantee of when the `*-local` hooks may get ran. If you run `make` it should be fine... but if you build parallel with say: `make -j8`  ... it's _possible_ that it gets output before a compile further down the line completes, so it isn't the last thing output in that case.

Generally with this structure, and the top-level being one up from any source it _should_ be fine... should being the key word though.

2018-01-17 09:04 UTC, olifre commented
> but there's no way building from source we can do the same thing unless we bail out if we don't find it during the ./configure stage.

Right. In general, it's also not the build system's job to check for any run time dependencies. 
Doing that and enforcing them to be present at build-time effectively makes them build time requirements needlessly - which means all packaging code should be adapted to have a `BuildRequires` on `squashfs-tools` if this check goes in as it is. Right now, it actively breaks all distro's packaging - so I wonder how it could pass @GodloveD s review. There's no other package I know of which does that - and if there was, distros would patch out those broken checks downstream and ask upstream to fix that in a future release, instead of adding wrong dependencies. 

In general, the way to go should be to document run time requirements. In any case, user's only have to take care if they don't use pre-built packages, and users not using packages from their distro should know what they are doing. 

The other option would be to have singularity check at runtime, but of course this comes at an additional cost, and it's questionable whether this should be done, when one can just expect users to read the docs.

2018-01-17 14:35 UTC, GodloveD commented
Ah.  That makes sense.  Thanks for the clarification @olifre.  I did not think to check distro packaging.  Only building from source.  I suppose this means Travis tests will fail momentarily.

2018-01-17 14:55 UTC, olifre commented
> I suppose this means Travis tests will fail momentarily.

Since the travis tests don't do correct packaging (c.f. https://github.com/singularityware/singularity/pull/1204 ), this might even go unnoticed. 
I'd say it's also wrong when building from source. 

Especially HPC users usually build on one build host machine, and install / deploy via a shared filesystem / cvmfs to many worker nodes. 
So checking for presence of `squashfs-tools` on the build machine is completely useless for all production usecases and just causes unnecessary installation of stuff on the build host. It may only be of interest in development environments, when build environment and usage environment coincide - but then, developers should know what they do.

2018-01-17 16:14 UTC, jmstover commented
@olifre In the latest commit, I removed the `configure.ac` check, and just did a hook on `all-local` to output a message after `make` is ran.

That should _hopefully_ satisfy everything. Something to say mksquashfs is required when doing a source build, and not breaking the dependency tree.

From what I was able to get, mksquashfs is required _everywhere_. Even some transitory images are created using mksquashfs ... so it has to be not only on the build host, but where singularity is ran at as well.

2018-01-17 16:20 UTC, olifre commented
> From what I was able to get, mksquashfs is required everywhere. Even some transitory images are created using mksquashfs ... so it has to be not only on the build host, but where singularity is ran at as well.

I believe it is not needed when sandbox images and unprivileged mode are used (main usecase of WLCG), but of course you are right: Both the "Singularity container build machine" and the "Singularity container execute machine" will need `mksquashfs`. 
Only the "Singularity compile machine", which could be a dedicated rpmbuild / debuild machine or build infrastructure in the cloud / from a Linux distribution will certainly not need it, and this is the major concern. 

So I believe now everything is fine, many thanks for your work on this! :smile:

2018-01-17 17:38 UTC, merged

2018-01-17 17:39 UTC, GodloveD commented
Thanks very much @jmstover for addressing this issue and to @olifre for taking the time to discuss and work through the tweaks.  Much appreciated.