Bad deffile
apptainer/singularity pull request #1373
Opened 2018-03-08 21:06 UTC by ArangoGutierrez

`ParseDefinitionFile` now returns error when a bad definition file.

Also fix the `_test.go` to work with the new version of the `ParseDefinitionFile`

Attn: @singularityware-admin

2018-03-12 15:37 UTC, bauerm97 requested changes
Hey Ed, just going to leave this here for reference since we discussed in slack already.

I fixed the merge conflicts in the branch I pushed to my fork, go ahead and use that as the base. Make the tests a little less cyclic as we discussed and then we can merge :)

2018-03-13 13:16 UTC, ArangoGutierrez commented
@bauerm97 check out commit: 
d992b89

2018-03-14 16:10 UTC, bauerm97 requested changes

2018-03-14 16:10 UTC, bauerm97 commented on pkg/build/definition_parser_deffile.go
> +			key = strings.ToLower(strings.TrimSpace(lineSubs[0]))
We can't use ToLower on these strings. File names are case sensitive. This will fail for any file that's not all lower case.

2018-03-14 16:13 UTC, ArangoGutierrez commented on pkg/build/definition_parser_deffile.go
> +			key = strings.ToLower(strings.TrimSpace(lineSubs[0]))
got it. fixing....>

2018-03-14 17:37 UTC, merged