fixed SINGULARITYENV_PATH and added SINGULARITYENV_APPEND_PATH and SINGULARITYENV_PREPEND_PATH
apptainer/singularity pull request #1430
Opened 2018-03-29 17:58 UTC by GodloveD

**Description of the Pull Request (PR):**

In the days of yore, a user could specify a value of `SINGULARITYENV_PATH` and this would be prepended to the `PATH` inside their container at runtime.  Some time ago, this option was broken by the addition of a file in `/.singularity.d/env` called `10-docker.sh` which overwrites the base path set in c with whatever path is set in Docker.  This is necessary because the user may have added custom paths to the container in the Docker file.  But it breaks `SINGULARITYENV_PATH`.

This PR will fix the problem for newly built containers and also give users the ability to overwrite and append to the container `PATH` at runtime with environment variables.  At build time, a new file will be added to the `/.singularity.d/env` directory called `99-runtimevars.sh`.  When running one of these newly built containers, the user can set these variables for the corresponding `PATH` adjustments.  

- `SINGULARITYENV_PATH` <- overwrite the container `PATH` at runtime.  (Note that this changes the old behavior which was to prepend the contents of the variable onto `PATH`.
- `SINGULARITYENV_PREPEND_PATH` <- prepend some new content to the container `PATH` at runtime
- `SINGULARITYENV_APPEND_PATH` <- append some new content to the container `PATH` at runtime

**This fixes or addresses the following GitHub issues:**

fixes #1352
see also #1363 and #1389 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-03-30 21:10 UTC, dctrud commented
This is giving correct behaviour for me.

**No Dockerfile custom path, No SINGULARITYENV_PATH**

```
singularity exec docker://alpine env | grep ^PATH=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**No Dockerfile custom path, Set SINGULARITYENV_PATH**
```
SINGULARITYENV_PATH=/opt singularity exec docker://alpine env | grep ^PATH= 
PATH=/usr/bin:/bin
```

**No Dockerfile custom path, Set SINGULARITYENV_APPEND_PATH**
```
SINGULARITYENV_APPEND_PATH=/opt singularity exec docker://alpine env | grep ^PATH= 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt
```

**No Dockerfile custom path, Set SINGULARITYENV_PREPEND_PATH**
```
SINGULARITYENV_PREPEND_PATH=/opt singularity exec docker://alpine env | grep ^PATH= 
PATH=/opt:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Dockerfile custom path, No SINGULARITYENV_PATH**
```
singularity exec docker://continuumio/miniconda env | grep ^PATH= 
PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Dockerfile custom path, Set SINGULARITYENV_PATH**
```
SINGULARITYENV_PATH=/usr/bin:/bin singularity exec docker://continuumio/miniconda env | grep ^PATH=
PATH=/usr/bin:/bin
```

**Dockerfile custom path, Set SINGULARITYENV_APPEND_PATH**
```
SINGULARITYENV_APPEND_PATH=/testpath singularity exec docker://continuumio/miniconda env | grep ^PATH=
PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/testpath
```

**Dockerfile custom path, Set SINGULARITYENV_PREPEND_PATH**
```
SINGULARITYENV_PREPEND_PATH=/testpath singularity exec docker://continuumio/miniconda env | grep ^PATH=
PATH=/testpath:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

2018-03-30 21:13 UTC, dtrudg requested changes
This is all working for me, but I think it is important this correct behaviour should really be captured in the test suite so we can guard against regressions going forward. Maybe the run commands in comment above give some test examples that can be worked from?

2018-03-30 21:13 UTC, dctrud commented on etc/init
> +# prepended, appended, or overwrite the PATH at runtime.
`prepend to, append to, or overwrite PATH at runtime`

2018-03-30 21:42 UTC, GodloveD commented
+1 on tests.  Will add tonight.  Also +1 on edits.  

BTW, your second test above seems a little weird right?  Is it a typo?  Did you mean something more like this?
```
$ SINGULARITYENV_PATH=/opt singularity exec docker://alpine /usr/bin/env | grep ^PATH=
PATH=/opt
```

2018-03-30 21:51 UTC, dctrud commented
If you just set /opt then the container won’t run - ‘env’ won’t be in PATH

Sent from my iPhone

> On Mar 30, 2018, at 4:42 PM, David Godlove <notifications@github.com> wrote:
> 
> +1 on tests. Will add tonight. Also +1 on edits.
> 
> BTW, your second test above seems a little weird right? Is it a typo? Did you mean something more like this?
> 
> $ SINGULARITYENV_PATH=/opt singularity exec docker://alpine /usr/bin/env | grep ^PATH=
> PATH=/opt
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-04-02 13:14 UTC, dtrudg approved these changes

2018-04-02 16:23 UTC, ctmadison approved these changes

2018-04-02 16:25 UTC, merged

2018-04-03 19:15 UTC, jakirkham commented
Does this mean 2.5 is on it's way? :)