Combined patch enhancing build system and overall structure
apptainer/singularity pull request #1484
Opened 2018-04-25 22:49 UTC by yhcote

2018-04-26 18:54 UTC, bauerm97 approved these changes
Looks good and builds correctly for me. Let's merge this now and then submit a new patch to fix some of the minor things suggested by @tri-adam

2018-04-27 01:57 UTC, dtrudg reviewed
Don't feel able to give a thumbs up or down on this.

Builds okay for me by running `./mconfig` - but how do I build or run an image?

`builddir/singularity` doesn't have any sub-commands available, and the new `sbuild` is asking for builder type, definition json etc. not a def file.

Have a few concerns about naming consistency which may be minor, or may be things that get annoying when things go along - but mainly, need some guidance here on what is the expected functionality that should be working, and how to test the binaries built.

2018-04-27 01:57 UTC, dctrud commented on src/cmd/singularity/actions.go
> +	runtimeconfig "github.com/singularityware/singularity/src/runtime/workflows/workflows/singularity/config"
Nested `worklfows/workflows` is going to get confusing - is there any other sensible naming here?

2018-04-27 01:57 UTC, dctrud commented on src/cmd/singularity/actions.go
> +	"github.com/singularityware/singularity/src/pkg/buildcfg"
Would prefer consistent use of config or cfg c.f. this line with the above

2018-04-27 01:57 UTC, dctrud commented on src/pkg/sif/sifcore.go
> +// #cgo LDFLAGS: -lruntime -luuid
Just wondering if there is any chance of bumping into some other lib called 'runtime' in a library path?

2018-04-27 13:56 UTC, tri-adam commented
I'm getting a warning from `dep` on this branch:

```
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  github.com/syndtr/gocapability

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies,
```

I think that constraint just needs to be removed from `Gopkg.toml`.

2018-04-27 17:48 UTC, bauerm97 requested changes
Updating my review since we need to make a few changes as pointed out by @dctrud. I failed to do my due diligence when reviewing; I make installed this branch into a non-pathed location and ended up doing my testing from a previous installation.

2018-04-30 01:50 UTC, bauerm97 approved these changes

2018-04-30 01:51 UTC, bauerm97 commented
I'm approving the updated changes and merging. Thanks @yhcote

2018-04-30 01:51 UTC, merged