headers format
apptainer/singularity pull request #1561
Opened 2018-05-18 21:26 UTC by ArangoGutierrez

On this PR:

 - Add missing headers
 - Fix format for some copyright headers
 - format some imports (`goimports` tool)

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-05-18 22:12 UTC, yhcote commented
I thought the standard was to use // for the copyrights at the top of the files ???

2018-05-18 22:32 UTC, tri-adam requested changes
I agree with @yhcote, let's use a format that is consistent with the Golang source itself:

```
// Copyright (c) 2018, Sylabs Inc. All rights reserved.
// This software is licensed under a 3-clause BSD license. Please consult the
// LICENSE file distributed with the sources of this project regarding your
// rights to use or distribute this software.
```

2018-05-18 22:33 UTC, ArangoGutierrez commented
`Go provides C-style /* */ block comments and C++-style // line comments. Line comments are the norm; block comments appear mostly as package comments, but are useful within an expression or to disable large swaths of code.`
[effective_go](https://golang.org/doc/effective_go.html#commentary)

2018-05-18 22:41 UTC, tri-adam commented
As it says, 

> Line comments are the norm

These are not package comments, nor an expression, nor a large swath of code to be disabled. Let's keep consistent with the Golang source, please.

2018-05-21 13:29 UTC, ArangoGutierrez commented
67703f1 changes all copyright headers to:
```go
// Copyright (c) 2018, Sylabs Inc. All rights reserved.
// This software is licensed under a 3-clause BSD license. Please consult the
// LICENSE file distributed with the sources of this project regarding your
// rights to use or distribute this software.
```
@tri-adam 
ready for a second pass.

2018-05-21 14:21 UTC, tri-adam requested changes

2018-05-21 14:21 UTC, tri-adam commented on src/cmd/singularity/cli/signing.go
> +	"os"
Remove space above this line?

2018-05-21 14:39 UTC, ArangoGutierrez commented on src/cmd/singularity/cli/signing.go
> +	"os"
`goimports` ... fixing

2018-05-21 14:45 UTC, tri-adam approved these changes

2018-05-21 14:45 UTC, merged