Issue 1680
apptainer/singularity pull request #1721
Opened 2018-07-03 18:10 UTC by oddodaoddo

**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Ref: #

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/ and this PR conforms to the stated requirements.
- [x ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x ] This PR is NOT against the project's master branch
- [x ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x ] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-07-03 18:29 UTC, jmstover commented on src/docker-extract.c
> +    singularity_message(DEBUG, "Available /tmp space %lu bytes\n", fs_avail_space);
Where `/tmp` is hard coded (and below), you should use `layer_target_fs` for the target... like:

`singularity_message(DEBUG, "Available %s space %lu bytes\n", layer_target_fs, fs_avail_space);`

2018-07-03 19:11 UTC, oddodaoddo commented
Sorry about that - I get excited about my first PR to be potentially accepted - I should pay more attention. Anyway, fixed and I re-ran make test and tested also in a VM with a restricted size /tmp...

Ognen

2018-07-05 20:27 UTC, dtrudg requested changes
Code looks good to me. Just some really picky comments r.e. getting the indentation consistent.

2018-07-05 20:27 UTC, dtrudg commented on src/docker-extract.c
> +
whitespace

2018-07-05 20:27 UTC, dtrudg commented on src/docker-extract.c
> +	singularity_message(WARNING, "Unable to estimate expanded size of archive %s or size is zero.\n", tarfile);
there's a mix of tabs and spaces for indentation in this area - please could you reconcile? Should be a 4 space indent in this file.

2018-07-05 21:03 UTC, oddodaoddo commented on src/docker-extract.c
> +	singularity_message(WARNING, "Unable to estimate expanded size of archive %s or size is zero.\n", tarfile);
Thanks! My primary machine is FreeBSD and singularity doesn't run on it ;-) so I develop in a Linux VM and I think my vi tab settings are all messed up. I sent a fix, hopefully that does it.

2018-07-05 21:44 UTC, dtrudg approved these changes

2018-08-04 01:29 UTC, closed without merging