Sif packer
apptainer/singularity pull request #1788
Opened 2018-07-24 23:33 UTC by ikaneshiro

Packer that uses the system partition of a SIF file as the rootfs for the bundle and subsequent build.

Attn: @singularityware-admin

2018-07-25 00:07 UTC, tri-adam requested changes
Two small suggestions. Tested against the new tests in #1774 and I'm not seeing any SIF-related failures there.

2018-07-25 00:07 UTC, tri-adam commented on src/pkg/build/packer_sif.go
> +	tmpmnt, err := ioutil.TempDir("/tmp", "tmpmnt-")
Is there a reason to explicitly use `/tmp`? I think we should probably leave that blank, that way users can override via `$TMPDIR` if necessary.

2018-07-25 00:07 UTC, tri-adam commented on src/pkg/build/packer_sif.go
> +	return err
Nitpick: could be `return nil` here, just makes it a bit clearer that you're exiting without an error at this point.

2018-07-25 00:25 UTC, tri-adam approved these changes

2018-07-25 00:31 UTC, merged

2018-07-26 20:58 UTC, yhcote reviewed
The lookup for the 3 types of FS could be done with GetFromDescr() which would probably shorten the code a bit but I recalled that I did not complete the descriptor specific field lookup. That will come later.

2018-07-26 20:58 UTC, yhcote commented on src/pkg/build/packer_sif.go
> +	fimg, err := sif.LoadContainer(rootfs, false)
The second parameter to LoadContainer() should be "true", because you do not modify the SIF file.