Fix environment variables clearing for instances
apptainer/singularity pull request #1800
Opened 2018-07-29 08:01 UTC by cclerget

**Description of the Pull Request (PR):**

Instances always clear environment variables, this PR fix that by changing the default behaviour to not clear environment variables by default and add `-e/--cleanenv` flag for `instance.start`

**This fixes or addresses the following GitHub issues:**

- Ref: #1766

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [ ] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-07-29 13:54 UTC, GodloveD requested changes
This looks good.  Would you also add this new option to `etc/bash_completion.d/singularity` for tab completion?

2018-07-29 21:14 UTC, GodloveD requested changes
Heya @cclerget I think it also needs to be added [here](https://github.com/cclerget/singularity/blob/751a39a04281308e16b6aa2f3f77be890394a867/etc/bash_completion.d/singularity#L325) so that tab completion works for both the dot and space version of the command.  I know that is really hacky.  sorry.  😄

2018-07-30 06:46 UTC, cclerget commented
Good catch, thanks @GodloveD !

2018-08-02 02:17 UTC, GodloveD approved these changes
lgtm

2018-08-02 02:20 UTC, yhcote approved these changes
lgtm

2018-08-02 02:20 UTC, merged