Development 3.0: Fix home mount with contain
apptainer/singularity pull request #1905
Opened 2018-08-30 13:24 UTC by cclerget

**Description of the Pull Request (PR):**

Fix issue #1891 and #1894

2018-08-30 14:30 UTC, ArangoGutierrez submitted a review, later dismissed
tested

2018-08-30 14:30 UTC, ArangoGutierrez commented on src/runtime/engines/singularity/container.go
> +// addHomeStagingDir adds the home staging directory in session directory and
is this comment incomplete?

2018-08-30 14:35 UTC, cclerget commented on src/runtime/engines/singularity/container.go
> +// addHomeStagingDir adds the home staging directory in session directory and
fixed

2018-08-31 02:02 UTC, GodloveD requested changes
This actually doesn't seem to fix #1891 

```
10:01 PM 
ubuntu ~/sandbox
$ singularity --version
singularity version 20758c4d

10:01 PM 
ubuntu ~/sandbox
$ singularity shell --home /data my_container
Singularity :/home/david/sandbox> pwd
/home/david/sandbox
```
In Singularity 2.6 that `pwd` command returns `/data`

2018-08-31 06:47 UTC, cclerget commented
@GodloveD Actually the code mount custom home but doesn't chdir into it since the current working directory is mounted with :
`cd $HOME/test && singularity shell --home /tmp/home my_container`

For the behaviour you described :

`cd $HOME/test && singularity shell --home /tmp/home:$HOME my_container`

I'm wondering if this is a bug to mount cwd with `--home` as long as cwd doesn't conflict with container home ?

2018-08-31 11:49 UTC, GodloveD commented
Oh I see.  Maybe this is just a bug in 2.6 then and we should _not_ `cd` to `$HOME` when we startup.  After all, we don't `cd` to `$HOME` when we start singularity without the `--home` option.  So that makes sense.  

But now I think the behavior is confusing the other way around.  Why do we `cd` to `$HOME` with this option argument pair?

```
--home /tmp/home:$HOME
```

Shouldn't we just stay in the `cwd` in that case too?  To be clear, the difference between these two commands doesn't make sense to me.

```
07:48 AM 
ubuntu ~/go/src/github.com/singularityware/singularity
$ cd ~/test

07:48 AM 
ubuntu ~/test
$ singularity exec --home /data:/mnt ~/sandbox/my_container pwd
/home/david/test

07:48 AM 
ubuntu ~/test
$ singularity exec --home /data:$HOME ~/sandbox/my_container pwd
/home/david
```

2018-08-31 14:25 UTC, cclerget commented
It depends where you are when you run Singularity, in your example you have `CWD=/home/david/test`, if you run with `--home /data:/home/david`, Singularity couldn't chdir to cwd because `/data` doesn't contain `test` directory path in order to bind it, that's why Singularity chdir goes into `/home/david`, if you create `/data/test` it should work with `CWD=/home/david/test`.

I agree this is confusing, and that may require to define a default behaviour after discussion

2018-08-31 14:45 UTC, jmstover commented
I thought current behavior was this:

1) `cd` to `$CWD` on host if possible
2) `cd` to `$HOME`
3) `cd` to `/`

So, if the host `$CWD` location is available, it wins; Then we fall back to `$HOME`; and finally `/`

2018-08-31 16:22 UTC, GodloveD commented
@jmstover I think that _should_ be the behavior.  But it doesn't look like it is the behavior?

2018-08-31 16:33 UTC, jmstover commented
This is what I get with 2.6.0

```
$ cd /tmp
$ /usr/local/singularity/2.6.0/bin/singularity exec ~/tmp/sing/centos7.img pwd
/tmp
$ /usr/local/singularity/2.6.0/bin/singularity exec -c ~/tmp/sing/centos7.img pwd
/home/jason
$ /usr/local/singularity/2.6.0/bin/singularity exec -c --no-home ~/tmp/sing/centos7.img pwd
WARNING: Could not chdir to home: /home/jason
/
```

So, $CWD, $HOME, then /

2018-08-31 16:45 UTC, bauerm97 commented
Just want to chime in and say that I agree with @jmstover here. I think that behavior should be:

1. `cd` to `$CWD`
2. `cd` to `$HOME`
3. `cd` to `/`

2018-08-31 17:27 UTC, jmstover commented
@GodloveD  ... This looks like it's working correctly to me:

```
$ cd /bin2
$ /usr/local/singularity/3.0.0-dev/bin/singularity exec ~/tmp/sing/alpine.sif pwd
/bin2
$ cd /tmp/
$ /usr/local/singularity/3.0.0-dev/bin/singularity exec -c ~/tmp/sing/alpine.sif pwd
/home/jason
$ /usr/local/singularity/3.0.0-dev/bin/singularity exec -c --no-home ~/tmp/sing/alpine.sif pwd
/
```

2018-09-01 20:38 UTC, GodloveD commented
I think you are right @jmstover.  In my second test above:

```
07:48 AM 
ubuntu ~/test
$ singularity exec --home /data:$HOME ~/sandbox/my_container pwd
/home/david
```

the `~/test` directory is no longer available and so it defaults to `$HOME`.  Thanks for clearing that up.

2018-09-01 20:38 UTC, GodloveD submitted a review, later dismissed

2018-09-01 20:39 UTC, GodloveD commented
@cclerget you've got two 👍 reviews now.  If you would like to resolve the conflicts and then merge, please feel free.  😸

2018-09-02 15:21 UTC, jmstover approved these changes

2018-09-03 18:23 UTC, GodloveD approved these changes
lgtm.  Thanks @ArangoGutierrez!

EDIT:  Whoops!  Put this approval and comment on the wrong PR I think.  This one is already good to go.

2018-09-03 18:28 UTC, merged