Fix issue #1938: Proper encoding and decoding of UTF8 paths
apptainer/singularity pull request #1958
Opened 2018-09-11 10:08 UTC by lckarssen

**Description of the Pull Request (PR):**

This commit fixes issue #1938: 'Problems when running some singularity commands in a directory with a non-ASCII character in its name' by adding proper encoding and decoding to/from UTF8 for various file-related functions.

Note: I ran `make test` on this code, but ran into differences between the Python 2 and 3 tests. Apparently the way encoding is handled by `write()` is different in these two versions (see [`message.py` line 182](https://github.com/singularityware/singularity/blob/vault/master-2.x/libexec/python/message.py#L182)).

Nevertheless, the changes in the PR work fine for my normal Singularity usage so far. 

**This fixes or addresses the following GitHub issues:**

- Ref: #1938 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [ ] This PR is against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-09-11 10:08 UTC, pep8speaks commented
Hello @lckarssen! Thanks for submitting the PR.

 - In the file [`libexec/python/shub/api.py`](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/shub/api.py), following                are the PEP8 issues :
> [Line 30:77](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/shub/api.py#L30): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 239:13](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/shub/api.py#L239): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\w'
> [Line 239:17](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/shub/api.py#L239): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\.'


 - In the file [`libexec/python/shub/main.py`](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/shub/main.py), following                are the PEP8 issues :
> [Line 26:77](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/shub/main.py#L26): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment


 - In the file [`libexec/python/sutils.py`](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/sutils.py), following                are the PEP8 issues :
> [Line 540:13](https://github.com/lckarssen/singularity/blob/a873961e91d3ee05bcc83736803666d86b1fdd70/libexec/python/sutils.py#L540): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\s'

2018-09-11 15:12 UTC, GodloveD requested changes
Hi @Ickarssen.  Thanks very much for the PR!  I have not tested it locally yet, but it looks like there are some problems that need to be fixed.

First, looks like this is not passing in Travis CI.  Can you investigate and fix please?  

Second can you please rebase onto release-2.6?  That is the correct branch for any point release bug fixes in the 2.6 series.

Finally, can you please add a comment to the CHANGELOG.md.  

Once this is fixed up I'll be happy to give it another look.  Thanks!

2018-11-08 19:27 UTC, GodloveD commented
Heya @lckarssen just wanted to check in with you.  Did you have any interest in continuing with this PR?

2018-11-11 22:19 UTC, lckarssen commented
Hi @GodloveD, unfortunately, I don't have time to pursue this at the moment. Especially since the affected Python files are no longer in v3.*/master.

2019-05-01 20:51 UTC, GodloveD commented
I don't think this is very relevant anymore.  Reopen or holler if I'm wrong.

2019-05-01 20:51 UTC, closed without merging