Build update option
apptainer/singularity pull request #1960
Opened 2018-09-11 15:47 UTC by ikaneshiro

This PR changes the `conveyor` interface to accept a `bundle` instead of a recipe to allow the build system to be run over a `bundle`. 

Builds occur as they have been before where if there is an existing container at the destination, there is an option to remove it or stop the build. The `--force` option defaults to remove the container at the destination.

This PR adds an `--update` option that skips the `conveyorPacker` portion, allowing builds with definitions to be run over an existing sandbox

2018-09-14 20:32 UTC, ArangoGutierrez submitted a review, later dismissed

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +	//if update, check for existing definition and move it to bootstrap history
`// if update, check for existing definition and move it to bootstrap history`

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +			//make bootstrap_history directory if it doesnt exist
`// make bootstrap_history directory if it doesnt exist`

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +			//look at number of files in bootstrap_history to give correct file name
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +			//name is "Singularity" concatinated with an index based on number of other files in bootstrap_history
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +			//move old definition into bootstrap_history
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +			//check for labels that already exist
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +			//add new labels to new map and check for collisions
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +					//overwrite collision if force flag is set
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +			//make new map into json
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/build.go
> +func (b Build) runPre() bool {
func name != comment name

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_arch_test.go
> +	//create bundle to build into
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_arch_test.go
> +	//create bundle to build into
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/pkg/sylog/sylog.go
> +// when --quiet option is set, this function returns ioutil.Discard writer to ignore output
```go
// Writer returns an io.Writer to pass to an external packages logging utility. 
// i.e when --quiet flag is set, this function returns ioutil.Discard writer to ignore output
```

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/runtime/engines/imgbuild/process.go
> +	//append environment
`//` + space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/runtime/engines/imgbuild/process.go
> +	//insert startscript
`// `+ space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/runtime/engines/imgbuild/process.go
> +	//insert runscript
`// `+ space

2018-09-14 20:32 UTC, ArangoGutierrez commented on src/runtime/engines/imgbuild/process.go
> +	//insert test script
`// `+ space

2018-09-15 20:08 UTC, bauerm97 requested changes

2018-09-15 20:08 UTC, bauerm97 commented on src/cmd/singularity/cli/build.go
> +			sylog.Errorf("Only sandbox updating is supported.")
`sylog.Fatalf` otherwise we keep going

2018-09-15 20:08 UTC, bauerm97 commented on src/pkg/build/build.go
> +	var err error
In here should do:

```
if update {
    format = "sandbox"
}
```

so users don't have to run `singularity build --update --sandbox ...`. It's already checked for in `cli/build.go` that the destination is a directory, so it's already implied.

2018-09-17 18:24 UTC, bauerm97 approved these changes

2018-09-17 18:36 UTC, merged