Support old images without /.singularity.d/actions/exec
apptainer/singularity pull request #1971
Opened 2018-09-12 22:42 UTC by DrDaveD

**Description of the Pull Request (PR):**

This PR restores the old behavior of 2.x when /.singularity.d/actions/exec does not exist in an old image.  Depends on pr #1970 to work exactly the same so that should be merged first.

**This fixes or addresses the following GitHub issues:**

None

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [x] This PR is against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-09-17 19:04 UTC, bauerm97 requested changes
Just a few really minor nitpicks here @DrDaveD

2018-09-17 19:04 UTC, bauerm97 commented on src/runtime/engines/singularity/process.go
> +			if args[1][0] != '/' {
I think this is checking for absolute path? Would rather use `filepath.IsAbs(args[1])` to check for maximum portability

2018-09-17 19:04 UTC, bauerm97 commented on src/runtime/engines/singularity/process.go
> +				for _, keyval:= range env {
Make sure you're running `gofmt` over your code, this shouldn't be `keyval:= ...` but rather `keyval := ...`.

2018-09-17 21:03 UTC, DrDaveD commented on src/runtime/engines/singularity/process.go
> +			if args[1][0] != '/' {
Ok I changed it to that, thanks.

2018-09-17 21:05 UTC, DrDaveD commented on src/runtime/engines/singularity/process.go
> +				for _, keyval:= range env {
Ah, I wasn't aware of go fmt, very useful.  I think travis should run it so updates do not get accepted unless it has been run.

2018-09-17 21:06 UTC, DrDaveD commented
I made requested changes and rebased on the current master.

2018-09-24 02:48 UTC, bauerm97 approved these changes
Looks good after requested changes were addressed

2018-09-24 19:32 UTC, merged

2018-09-24 19:32 UTC, GodloveD commented
Thanks @DrDaveD !