Add pull tests from tri-adam
apptainer/singularity pull request #1985
Opened 2018-09-14 01:38 UTC by jscook2345

**Description of the Pull Request (PR):**

Add some pull tests originally created by @tri-adam . Close #1793.

- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [X] I have tested this PR locally with a `make test`
- [X] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [X] This PR is ready for review and/or merge

2018-09-14 01:53 UTC, ArangoGutierrez requested changes
small change

2018-09-14 01:53 UTC, ArangoGutierrez commented on src/cmd/singularity/pull_test.go
> +// LICENSE file distributed with the sources of this project regarding your
LICENSE.md
or @jmstover get angry

2018-09-14 02:18 UTC, ArangoGutierrez requested changes
small nitpick, that could save some seconds when testing

2018-09-14 02:18 UTC, ArangoGutierrez commented on src/cmd/singularity/pull_test.go
> +	if b, err := imagePull(pullOpts{}, "library://dtrudg/linux/ubuntu:17.10"); err != nil {
I recommend using `linux/alpine:3.7`

2018-09-14 02:18 UTC, ArangoGutierrez commented on src/cmd/singularity/pull_test.go
> +	imagePath := "./ubuntu_17.10.sif"
`alpine_3.7.sif`

2018-09-14 02:18 UTC, ArangoGutierrez commented on src/cmd/singularity/pull_test.go
> +	if b, err := imagePull(pullOpts{}, "library://dtrudg/linux/ubuntu:17.10"); err == nil {
I recommend using `linux/alpine:3.7`

2018-09-14 02:18 UTC, ArangoGutierrez commented on src/cmd/singularity/pull_test.go
> +	if b, err := imagePull(pullOpts{force: true}, "library://dtrudg/linux/ubuntu:17.10"); err != nil {
same: I recommend using `linux/alpine:3.7`

2018-09-15 11:27 UTC, ArangoGutierrez approved these changes

2018-09-15 11:59 UTC, ArangoGutierrez commented
@tri-adam  RFR

2018-09-15 17:19 UTC, tri-adam commented
I can't approve this (I wrote it) but one review is enough. Thanks gents.

2018-09-15 17:19 UTC, merged