Development 3.0: Fix instance stop
apptainer/singularity pull request #1993
Opened 2018-09-14 23:35 UTC by cclerget

**Description of the Pull Request (PR):**

This PR fixes `instance stop` command from stopping all instances

**This fixes or addresses the following GitHub issues:**

- Ref: #1990 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

2018-09-14 23:56 UTC, jmstover approved these changes

2018-09-15 03:23 UTC, bauerm97 requested changes

2018-09-15 03:23 UTC, bauerm97 commented on src/cmd/singularity/cli/instance_stop.go
>  		if len(args) > 0 && !stopAll {
Should be using `Command.Args: ExactArgs(1)` here instead of manually checking argument length. https://godoc.org/github.com/spf13/cobra#ExactArgs

2018-09-15 21:33 UTC, cclerget commented on src/cmd/singularity/cli/instance_stop.go
>  		if len(args) > 0 && !stopAll {
The problem with ExactArgs or MinimumNArgs is that flag are not taken into account during processing, so `singularity instance stop -a` always display help with 1 arg missing. Will check if cobra support this without manual check.

2018-09-16 00:58 UTC, bauerm97 commented on src/cmd/singularity/cli/instance_stop.go
>  		if len(args) > 0 && !stopAll {
Good point, actually think in this case is okay then. Will go ahead and merge :)

2018-09-16 00:58 UTC, bauerm97 approved these changes

2018-09-16 01:00 UTC, bauerm97 requested changes

2018-09-16 01:00 UTC, bauerm97 commented on src/cmd/singularity/cli/instance_stop.go
> +			sylog.Fatalf("no arguments supplied")
Actually, would like to see this:

`cmd.Usage()` instead of `sylog.Fatalf()`

2018-09-16 01:38 UTC, bauerm97 approved these changes

2018-09-16 01:42 UTC, merged