Add singularity env tests
apptainer/singularity pull request #2004
Opened 2018-09-17 16:47 UTC by jscook2345

**Description of the Pull Request (PR):**

Porting of 25-environment.sh test to new Go framework

**This fixes or addresses the following GitHub issues:**

Closes #2001 

**Checkoff for all PRs:**

- [ ] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [X] I have tested this PR locally with a `make test`
- [X] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [X] This PR is ready for review and/or merge

Attn: @singularityware-admin

2018-09-19 23:41 UTC, bauerm97 submitted a review, later dismissed

2018-09-19 23:41 UTC, bauerm97 commented on src/cmd/singularity/env_test.go
> +	if os.Getenv("TEST_26") == "" {
Should rather use the accepted way to skip disabled tests

```
	if !*runDisabled {
		t.Skip("disabled until issue addressed") // TODO
	}
```

2018-09-19 23:42 UTC, bauerm97 commented on src/cmd/singularity/env_test.go
> +	if os.Getenv("TEST_26") == "" {
`go test --run_disabled ...` flag is defined in `src/cmd/singularity/cli_test.go`

2018-09-21 22:11 UTC, ArangoGutierrez requested changes

2018-09-21 22:11 UTC, ArangoGutierrez commented on src/cmd/singularity/env_test.go
> +	"github.com/singularityware/singularity/src/pkg/test"
update to sylabs

2018-09-21 23:50 UTC, ArangoGutierrez approved these changes

2018-09-22 00:21 UTC, ArangoGutierrez commented
@bauerm97 <- b46bce0
RFR

2018-09-22 03:01 UTC, ikaneshiro approved these changes

2018-09-22 03:58 UTC, jscook2345 commented
I'm ready for this to be merged. If #2045 is merged first, I can test that than rebase to merge this.

2018-09-22 04:06 UTC, bauerm97 commented
@jscook2345 Just merged #2045, go ahead and do that rebase and then it's good to go

2018-09-22 12:01 UTC, merged