Zypper conveyorPacker
apptainer/singularity pull request #2042
Opened 2018-09-21 01:09 UTC by ikaneshiro

Conveyor Packer that allows for bootstrapping with zypper.

Currently allows zypper bootstrapping to exit with errno 107. This indicates package installation was pretty much successful, but post installation scripts exited with errors. This can be removed based on feedback on this PR.

2018-09-21 01:33 UTC, ArangoGutierrez requested changes

2018-09-21 01:33 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +// LICENSE file distributed with the sources of this project regarding your
.md

2018-09-21 02:40 UTC, ArangoGutierrez requested changes

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	// //check for rpm on system
double //

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//check for include environment variable and add it to requires string
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//trim leading and trailing whitespace
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//add aaa_base to start of include list by default
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//Create the main portion of zypper config
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//Add mirrorURL as repo
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//Refreshing gpg keys
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//Zypper install command
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//run zypper
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +
white line

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +
white line

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//look for an OS version if the mirror specifies it
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	//get mirrorURL, OSVerison, and Includes components to definition
`//` + space

2018-09-21 02:40 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +	// //check for rpm on system
and `//` + space

2018-09-22 02:45 UTC, ArangoGutierrez submitted a review, later dismissed

2018-09-22 02:45 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper_test.go
> +
white line

2018-09-22 02:45 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper_test.go
> +	test.EnsurePrivilege(t)
`test.EnsurePrivilege(t)` should go on the first line of the func (niptick)

2018-09-22 02:45 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper_test.go
> +
white line

2018-09-22 02:45 UTC, ArangoGutierrez commented on src/pkg/build/sources/conveyorPacker_zypper_test.go
> +	test.EnsurePrivilege(t)
same as above

2018-09-23 01:10 UTC, ArangoGutierrez commented
This PR LGTM, I don't have Open Suse to test it on dep

2018-09-23 02:58 UTC, GodloveD submitted a review, later dismissed
I tried this on leap 42.3 and I got a panic.  Here's the stack trace.  Does this look like something I did or is there a bug?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9f6f99]

goroutine 1 [running]:
github.com/sylabs/singularity/src/pkg/build/sources.(*ZypperConveyorPacker).Get(0xc000482680, 0xc0000be640, 0x0, 0x0)
	/home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/sources/conveyorPacker_zypper.go:113 +0xbd9
github.com/sylabs/singularity/src/pkg/build.(*Build).Full(0xc0000be500, 0x1d, 0x7ffe614eee73)
	/home/vagrant/go/src/github.com/sylabs/singularity/src/pkg/build/build.go:156 +0xda
github.com/sylabs/singularity/src/cmd/singularity/cli.glob..func4(0x143c800, 0xc0004764c0, 0x2, 0x2)
	/home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/build.go:106 +0x4d2
github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).execute(0x143c800, 0xc0000300e0, 0x2, 0x2, 0x143c800, 0xc0000300e0)
	/home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x143f9e0, 0xc0004c5f88, 0x4078c0, 0xc00003a0b8)
	/home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).Execute(0x143f9e0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/sylabs/singularity/src/cmd/singularity/cli.ExecuteSingularity()
	/home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli/singularity.go:100 +0x2d
main.main()
	/home/vagrant/go/src/github.com/sylabs/singularity/src/cmd/singularity/cli.go:16 +0x20
```

2018-10-04 23:14 UTC, ArangoGutierrez commented
any update on this `WIP` ?

2018-10-05 19:40 UTC, ikaneshiro commented
@ArangoGutierrez Not yet. Hoping to knock this out over the next day or two

2018-10-06 18:55 UTC, ikaneshiro commented
The major issue encountered while developing and testing this feature was an exit 107 from Zypper due to the device-mapper package generating an error in its post script. This is fixed by bootstrapping with an openSUSE version of 42.3 or newer. I think this issue hasn't been encountered in past (to my knowledge) due to the 107 error code being a new addition to Zypper, meaning older versions of Zypper would not throw an error in this scenario. I suspect this is why bootstrapping with versions older than 42.3 appears to work on older openSUSE systems. As a result I have updated the openSUSE example definition to use 42.3 in order to avoid this error on systems using newer versions of Zypper

2018-10-06 19:09 UTC, ikaneshiro commented
@ArangoGutierrez @jscook2345 @GodloveD @bauerm97 RFR

2018-10-23 18:38 UTC, jscook2345 commented on src/pkg/build/sources/conveyorPacker_zypper.go
> +			"More info: https://github.com/singularityware/singularity/issues/241\n",
sylabs/singularity

2018-10-23 21:48 UTC, jscook2345 commented
My tests pass on suse but it *requires* the special macros in /root/.rpmmacros. The verbose output is still pretty scary looking to. Things like 'root: user does not exist' etc are still present.

2018-11-02 15:10 UTC, ikaneshiro commented
@jscook2345 sorry for the latency! 

After looking into the special macros issue I can't think of a better way to handle this ATM. Since there seems to be a lot of issues around the location of `_dbpath` being varied by package managers.

WRT the scary output. I don't know how much that can be fixed. It looks like using a newer version like 15.1  instread of 43.2 it doesn't have the `root: user does not exist` related warnings when I build on my VM. Maybe I should bump up the version in the example definition?

2018-11-05 14:26 UTC, jscook2345 commented
<pre>
FATAL:   While performing build: conveyor failed to get: RPM database is using a weird path: %{_usr}/lib/sysimage/rpmYou are probably running this bootstrap on Debian or Ubuntu.
</pre>

You're missing a newline here.

Can we also say 'non-standard path' location instead of 'weird path'. Also I think its OK to remove the comment about bootstrapping from other OSes.

2018-11-05 14:27 UTC, jscook2345 commented
<pre>
Warning: Checking for file conflicts requires not installed packages to be downloaded in advance in order to access their file lists. See option '--download-in-advance' in the zypper manual page for details.
</pre>

Perhaps we should enable / use this option?

2018-11-05 14:57 UTC, jscook2345 commented
I think after those last comments are fixed we can rebase and merge this assuming tests pass

2018-11-05 15:01 UTC, ikaneshiro commented
Ill make the changes mentioned in both comments. I think having the check for file conflicts is a good idea

2019-01-24 12:55 UTC, ArangoGutierrez commented
Any update here @ikaneshiro ?

2019-01-28 18:30 UTC, ikaneshiro commented
@ArangoGutierrez So, I've been thinking about whether requiring a certain `.rpmmacros` configuration is necessary or not. I haven't been able explicitly find a case where it's needed, but I have a hunch that this will help prevent potential rpmdb incompatibilities between host and container package managers. This `.rpmmacros` requirement is also present in 2.x.

TLDR: I think this PR is ready to be merged once its passing CI

2019-01-28 19:25 UTC, ArangoGutierrez commented
waaaahoooo
thanks for the update @ikaneshiro

2019-01-28 20:05 UTC, ArangoGutierrez requested changes

2019-01-28 20:05 UTC, ArangoGutierrez commented on internal/pkg/build/sources/conveyorPacker_zypper.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
2018-2019

2019-01-28 20:05 UTC, ArangoGutierrez commented on internal/pkg/build/sources/conveyorPacker_zypper_test.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
2018-2019

2019-01-28 20:35 UTC, ikaneshiro commented on internal/pkg/build/sources/conveyorPacker_zypper.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
good catch

2019-01-31 10:04 UTC, ArangoGutierrez commented
PR work , I will leave @GodloveD and @jmstover how to better handle 
```
There is a way to work around this problem:
Create a file at path /root/.rpmmacros.
Place the following lines into the '.rpmmacros' file:
%_var /var
%_dbpath %{_var}/lib/rpm
After creating the file, re-run the bootstrap.
```
via user documentation maybe?

2019-01-31 10:05 UTC, ArangoGutierrez approved these changes
LGTM

2019-01-31 16:36 UTC, merged