Adding default build flags
apptainer/singularity pull request #2047
Opened 2018-09-21 14:14 UTC by ikaneshiro

Adds things like boostrap header information, build time and singularity version used to build
fixes #2033

```singularity shell test.sif
Singularity> cat /.singularity.d/labels.json 
{
	"org.label-schema.build-date": "Friday_21_September_2018_10:10:56_EDT",
	"org.label-schema.schema-version": "1.0",
	"org.label-schema.usage": "/.singularity.d/runscript.help",
	"org.label-schema.usage.singularity.deffile.bootstrap": "docker",
	"org.label-schema.usage.singularity.deffile.from": "alpine",
	"org.label-schema.usage.singularity.runscript.help": "/.singularity.d/runscript.help",
	"org.label-schema.usage.singularity.version": "v3.0.0-alpha.2-44-gd6ec242b"
}

2018-09-21 15:24 UTC, ArangoGutierrez requested changes

2018-09-21 15:24 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +
white line

2018-09-21 15:24 UTC, ArangoGutierrez commented on src/pkg/build/assemblers/assembler_sandbox.go
> +
white line

2018-09-22 02:45 UTC, GodloveD requested changes
These changes do add labels to a container when built.  But now the `%labels` section doesn't seem to work anymore.

2018-09-22 18:14 UTC, ikaneshiro commented
@GodloveD That should be fixed now

2018-09-22 20:52 UTC, bauerm97 commented
@GodloveD can you please check if bug is fixed, also would be great if we could add a test to catch this regression ;) @ikaneshiro

2018-09-22 20:54 UTC, GodloveD commented
I was just looking at it.  Seems to behave as advertised now.

2018-09-22 20:54 UTC, GodloveD approved these changes

2018-09-22 21:44 UTC, ArangoGutierrez approved these changes

2018-09-22 23:52 UTC, merged