Clean build environment
apptainer/singularity pull request #2161
Opened 2018-10-03 16:34 UTC by ikaneshiro

Uses 'SetContainerEnv()` to clean the environment that the build engine runs in. This requires the use of a `generator` to configure the `ociConfig`, so that was added.

Fixes #2103

2018-10-03 19:33 UTC, ArangoGutierrez requested changes

2018-10-03 19:33 UTC, ArangoGutierrez commented on src/pkg/build/build.go
> +	env.SetContainerEnv(&generator, environment, true, "")
We need to move this from here, in order to respect `%setup` section, which should be for stuff that happens on the host before build.
test it with 
```
BootStrap: busybox
MirrorURL: https://www.busybox.net/downloads/binaries/1.26.1-defconfig-multiarch/busybox-x86_64

%setup
    env
    env > /tmp/pre_build_env

%post
    echo "Hello from inside the container"
    echo $PWD
    env > /tmp/build_env

%runscript
    echo "Running command: $*"
    exec "$@"
```

2018-10-04 15:31 UTC, ArangoGutierrez commented on src/runtime/engines/imgbuild/process.go
> +	// clean environment that post script is run in
Niptick 
```go
// clean environment on which  %post section script is run in
```

2018-10-04 15:32 UTC, ArangoGutierrez approved these changes

2018-10-04 15:42 UTC, ArangoGutierrez approved these changes

2018-10-04 19:37 UTC, bauerm97 approved these changes

2018-10-04 23:49 UTC, merged