Rewrite starter log message
apptainer/singularity pull request #2271
Opened 2018-10-20 00:32 UTC by cclerget

**Description of the Pull Request (PR):**

This PR rewrites C starter log message code, address issue #2212 and finally align debug output with Go sylog package.

**This fixes or addresses the following GitHub issues:**

- Fixes #2212 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2018-10-22 17:20 UTC, bauerm97 requested changes

2018-10-22 17:20 UTC, bauerm97 commented on src/runtime/c/lib/util/message.c
> + * project regarding your rights to use or distribute this software.
We can't remove the `Regents of the University of California...` section of the copyright. This file is coming from the previous version which was developed with that copyright header so it must remain.

2018-10-22 17:20 UTC, bauerm97 commented on src/runtime/c/lib/util/message.h
> + * project regarding your rights to use or distribute this software.
Same comment about copyright here.

2018-10-23 16:58 UTC, bauerm97 commented on src/runtime/c/lib/util/message.c
>   * Copyright (c) 2017, SingularityWare, LLC. All rights reserved.
I think (@gmkurtzer or @jmstover correct me if I'm wrong) that we no longer need to include the SingularityWare copyright line, as when Sylabs was created we transferred all IP from SingularityWare -> Sylabs. So we should remove the SingularityWare line, and update the Sylabs line to be:

`Copyright (c) 2017-2018, Sylabs Inc. All rights reserved.`

2018-10-23 17:10 UTC, bauerm97 submitted a review, later dismissed
I think after one small change to the copyright header this is good to go!

2018-10-24 17:05 UTC, cclerget commented
@bauerm97 Fixed, thanks !

2018-10-28 00:41 UTC, yhcote approved these changes
LGTM

2018-10-28 00:41 UTC, merged