Add dist/rpm/singularity.spec to .gitignore
apptainer/singularity pull request #2311
Opened 2018-10-27 16:31 UTC by bauerm97

2018-10-27 20:11 UTC, yhcote requested changes
This Cannot be done. The make-dist.sh script requires this file to be stage-able by git in order for archive inclusion.

I recommend to simply cancel that PR

2018-10-30 18:58 UTC, yhcote commented
I think that a form of this could be done soon as we reworked how we generate the release archive. Hold on...

2018-10-30 20:50 UTC, yhcote approved these changes
This works now. The file is actually generated in $sourcedir now.

2018-10-30 21:01 UTC, jmstover approved these changes

2018-10-30 21:18 UTC, merged