Types Package Refactor
apptainer/singularity pull request #2364
Opened 2018-11-14 19:36 UTC by ikaneshiro

**Description of the Pull Request (PR):**

- Types and Parser package refactoring
- Support for repeated sections in definitions
- Parser now throws an error when encountering a non-standard section that can be handled at a higher level

**This fixes or addresses the following GitHub issues:**

- Fixes #2308 
- Fixed #2349 
- Related to #2320 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2018-11-28 17:46 UTC, bauerm97 requested changes
Two small changes I point out here, then also we discussed adding a `Raw string` field to the definition file type to maintain all comments and formatting.

2018-11-28 17:46 UTC, bauerm97 commented on internal/pkg/build/sources/conveyorPacker_library.go
> +	sytypes "github.com/sylabs/singularity/pkg/build/types"
Why is this the only place we're importing as `sytypes`?

2018-11-28 17:46 UTC, bauerm97 commented on internal/pkg/build/sources/conveyorPacker_shub.go
> +	sytypes "github.com/sylabs/singularity/pkg/build/types"
Same question here as above, any reason to import as `sytypes`?

2018-12-18 21:19 UTC, ikaneshiro commented
@bauerm97 RFR

2018-12-19 17:41 UTC, bauerm97 requested changes

2018-12-19 17:41 UTC, bauerm97 commented on pkg/build/types/definition.go
> +func WriteDefinitionFile(d *Definition, w io.Writer) {
Maybe this can just be replaced by writing out the new `Definition.Raw` field

2018-12-19 17:41 UTC, bauerm97 commented on pkg/build/types/definition.go
> +	RawDefData []byte            `json:"rawDefData"`
I think `Definition.RawDefData` is a bit too terse. Maybe just `Definition.Raw`

2018-12-20 18:22 UTC, bauerm97 commented on pkg/build/types/definition.go
> +	n, err := w.Write(d.Raw)
Well, this causes a big problem it turns out. We use `WriteDefinitionFIle` on line `103` in this file to fill the `d.Raw` when the spec is not a def file, but rather a URI without a def file. This means that when doing `singularity shell docker://ubuntu`, for example, the `d.Raw` will be nil which breaks the creation of the SIF.

2018-12-21 15:48 UTC, bauerm97 approved these changes

2018-12-21 16:20 UTC, merged