Allow username/password docker auth
apptainer/singularity pull request #2392
Opened 2018-11-27 14:08 UTC by ikaneshiro

**Description of the Pull Request (PR):**

Use `SINGULARITY_DOCKER_USERNAME` and `SINGULARITY_DOCKER_PASSWORD` for docker authentication when both are present.

**This fixes or addresses the following GitHub issues:**

- Fixes #2384

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2018-12-06 20:40 UTC, jmstover commented on internal/pkg/build/sources/conveyorPacker_oci.go
> +	ocitypes "github.com/containers/image/types"
Is there a reason to import this again under the `ocitypes` name instead of just using `types` as is being done elsewhere?

2018-12-07 20:25 UTC, bauerm97 requested changes
I think this is mostly there, just some small nitpicks

2018-12-07 20:25 UTC, bauerm97 commented on cmd/singularity/cli/build_linux.go
> +		if !cmd.Flags().Lookup("docker-username").Changed {
I think that `cmd.Flags().Lookup("docker-username")` part should be pulled out into a variable:

`userFlag := cmd.Flags().Lookup("docker-username")` as well as for password. Just so that we don't have to spend the (probably negligible) amount of time repeatedly calling `Lookup()`

2018-12-07 20:25 UTC, bauerm97 commented on cmd/singularity/cli/build.go
> +	BuildCmd.Flags().StringVar(&dockerUsername, "docker-username", "", "specify a username for docker authentication")
These are all duplicates of the `actionFlags.Flags()...` flags. I feel like we don't need to have duplicate lines of this code, just use `BuildCmd.Flags().AddFlag(actionFlags.Lookup(...))` instead

2018-12-07 20:25 UTC, bauerm97 commented on cmd/singularity/cli/pull.go
> +	PullCmd.Flags().StringVar(&dockerUsername, "docker-username", "", "specify a username for docker authentication")
Same comment here as with `BuildCmd`

2018-12-07 20:25 UTC, bauerm97 commented on cmd/singularity/cli/pull_linux.go
> +		authConf, err := makeDockerCredentials(cmd)
Will `makeDockerCredentials` return `nil, nil` in the case where the environment variables aren't present AND `--docker-login` is not specified?

2018-12-07 20:25 UTC, bauerm97 commented on cmd/singularity/cli/singularity.go
> +	if flag.Changed == false {
Removing `envvar != ""` here for the `envBool` parsing might cause certain people's workflows to break unexpectedly if they are (for some weird reason) explicitly setting a bool var to false. Just something to think about

2018-12-07 22:30 UTC, ikaneshiro commented on cmd/singularity/cli/build_linux.go
> +		if !cmd.Flags().Lookup("docker-username").Changed {
Done

2018-12-07 22:30 UTC, ikaneshiro commented on cmd/singularity/cli/build.go
> +	BuildCmd.Flags().StringVar(&dockerUsername, "docker-username", "", "specify a username for docker authentication")
Done

2018-12-07 22:30 UTC, ikaneshiro commented on cmd/singularity/cli/pull.go
> +	PullCmd.Flags().StringVar(&dockerUsername, "docker-username", "", "specify a username for docker authentication")
Done

2018-12-07 22:30 UTC, ikaneshiro commented on cmd/singularity/cli/pull_linux.go
> +		authConf, err := makeDockerCredentials(cmd)
Yes

2018-12-07 22:30 UTC, ikaneshiro commented on cmd/singularity/cli/singularity.go
> +	if flag.Changed == false {
Good point, fixed

2018-12-09 16:25 UTC, bauerm97 commented on cmd/singularity/cli/singularity.go
> +		sylog.Debugf("Unable to set %s to environment variable value %s", flag.Name, envvar)
Small tweak:

``sylog.Debugf("Unable to set flag %s to value %s: %s", flag.Name, envvar, err)``

2018-12-09 16:26 UTC, bauerm97 commented on cmd/singularity/cli/singularity.go
>  			sylog.Warningf("Unable to set %s to true", flag.Name)
I think the same message as above is justifiable here.

2018-12-09 16:28 UTC, bauerm97 commented on cmd/singularity/cli/singularity.go
> +		sylog.Warningf("Unable to set %s to environment variable value %s", flag.Name, envvar)
Same comment as warning message above

2018-12-09 16:29 UTC, bauerm97 commented on cmd/singularity/cli/singularity.go
> +	sylog.Debugf("Update flag Value to: %s", flag.Value)
Maybe should use same debug message as above:

`sylog.Debugf("Set %s Value to: %s", flag.Name, flag.Value)`

2018-12-09 16:34 UTC, bauerm97 requested changes
Left a few comments

2018-12-09 17:23 UTC, bauerm97 commented on cmd/singularity/cli/singularity.go
> +		sylog.Debugf("Unable to set flag %s to value %s: %s", flag.Name, envvar, err)
This should still be `sylog.Warningf`, no?

2018-12-09 17:31 UTC, ikaneshiro commented on cmd/singularity/cli/singularity.go
> +		sylog.Debugf("Unable to set flag %s to value %s: %s", flag.Name, envvar, err)
Do we want a warning if it will just default to `true`? Figured it'd be more for debugging

2018-12-12 20:11 UTC, ikaneshiro commented
@GodloveD Just tested with NVIDIA cloud and it works :+1:

2018-12-12 20:37 UTC, bauerm97 approved these changes
I think my comments have been addressed.

2018-12-13 15:31 UTC, merged

2018-12-13 17:38 UTC, tamasgal commented
Good news! Will this be available in singularly 2?

2018-12-13 17:47 UTC, jmstover commented
@tamasgal .... Singularity 2.x should have this. It was missed on the 3.0 code rewrite.

2018-12-13 17:54 UTC, tamasgal commented
Hm, my issue which is now also closed was referring I singularity 2, so that is not fixed than :-/

2018-12-13 17:56 UTC, tamasgal commented
Sorry, it is not closed: https://github.com/sylabs/singularity/issues/2377

So is this related to that issue?

2018-12-14 13:49 UTC, GodloveD commented
@tamasgal are you able to test the current master branch and see if it works for this?

2018-12-14 14:23 UTC, tamasgal commented
@GodloveD I can do this on Sunday probably. But since it's a public repository, anyone should be able to check it. For example this should work out of the box (no login required):

    docker run -it docker.km3net.de/km3pipe

and this is what does not work with Singularity 2.6.x:

    singularity pull docker://docker.km3net.de/km3pipe

I'd assume when the docker pull works, Singularity pull should work too ;)

2018-12-14 16:44 UTC, tamasgal commented
I just had the opportunity to test it with 3.0.1 and it works.

Of course this does not solve the 2.6.x issue but at least I can now build the singularity images.

2018-12-17 15:39 UTC, GodloveD commented
heya @tamasgal.  Thanks very much for verifying that the current master does not have this bug.  Development efforts are mainly being spent on the 3.x series now.  I don't think there is much of an appetite to backport bug fixes to the 2.x series since it is not officially supported anymore.

2018-12-17 18:29 UTC, tamasgal commented
Ok thanks, I'll then wait for our HPC admins to update singularity...

Cheers!