Child images inherit parent environment
apptainer/singularity pull request #2510
Opened 2018-12-31 16:05 UTC by ikaneshiro

**Description of the Pull Request (PR):**

This PR adds a check to see if the base image has an environment.sh script and appends to it if it does. This allows child images to maintain the environment of the parent like in 2.x.

**This fixes or addresses the following GitHub issues:**

- Fixes #2443 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-01-10 02:42 UTC, al3x609 commented
hi all, 
Do not forget about merge this. :(

2019-01-14 21:14 UTC, bauerm97 requested changes
Add those newlines and we're good

2019-01-14 23:15 UTC, bauerm97 approved these changes

2019-01-15 00:48 UTC, merged

2019-01-18 02:04 UTC, GodloveD commented
👍