Build package initial refactor for multistage
apptainer/singularity pull request #2524
Opened 2019-01-08 20:05 UTC by ikaneshiro

**Description of the Pull Request (PR):**

Introduces the `stage` struct to the build package. This encapsulates the data needed to perform the building of a stage. Allowing the `Build` struct to hold a slice of `stage`s to be build in order when `deffile` syntax is expanded to allow for multiple `bootstraps` in a single file.

Introduces the `Config` struct to the build package. This contains build information as well as a `types.Options` struct to pass on information to newly constructed `bundles`

Moved `libraryURL` and `authToken` to `types.Options` struct since this data should exist in the `Bundle`

Created a `metadata.go` file to hold helper functions that assist the insertion of metadata to a `Bundle` during the build process.

Minor additional refinements.

**This fixes or addresses the following GitHub issues:**

- Related to #2518

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-01-09 21:20 UTC, ArangoGutierrez commented
Heya @ikaneshiro , I know this is still tagged as WIP, but,  pls don't forget about testing ;) 
Cheers

2019-03-22 16:05 UTC, WestleyK reviewed
Minor suggestions for the copyright year, otherwise looks good!

2019-03-22 16:05 UTC, WestleyK commented on internal/pkg/build/metadata.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
2019?

```suggestion
// Copyright (c) 2018-2019, Sylabs Inc. All rights reserved.
```

Or:

```suggestion
// Copyright (c) 2019, Sylabs Inc. All rights reserved.
```

2019-03-22 16:05 UTC, WestleyK commented on internal/pkg/build/sources/conveyorPacker_library.go
> +	libraryURL := b.Opts.LibraryURL
I would update the copyright in this file, `2018-2019`.

2019-03-22 16:05 UTC, WestleyK commented on internal/pkg/build/stage.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
Update copyright:

```suggestion
// Copyright (c) 2018-2019, Sylabs Inc. All rights reserved.
```

Or:

```suggestion
// Copyright (c) 2019, Sylabs Inc. All rights reserved.
```

2019-03-22 16:05 UTC, WestleyK commented on internal/pkg/build/stage.go
> +// Stage ...
Is there more to this comment?

2019-03-22 16:05 UTC, WestleyK commented on internal/pkg/libexec/pull.go
> +	b, err := build.NewBuild(uri, build.Config{Dest: path, Format: "sif", Opts: opts})
I would update the copyright in this file: `2018-2019`. *I cant comment that line, github wont let me.*

2019-03-22 16:05 UTC, WestleyK commented on pkg/build/types/bundle.go
> +	// sections are the parts of the definition to run during the build
Update copyright in this file too.

2019-03-25 14:56 UTC, bauerm97 requested changes

2019-03-25 14:56 UTC, bauerm97 commented on pkg/build/types/bundle.go
> +	// sections are the parts of the definition to run during the build
Can we actually write a comment on this type please?

2019-03-25 14:56 UTC, bauerm97 commented on internal/pkg/build/build.go
> +// Config ...
And not to rain on the parade, but let's comment this as well

2019-03-25 14:56 UTC, bauerm97 commented on internal/pkg/build/build.go
> +	Dest string
The comment on this field should also be updated to match the case

2019-03-25 14:56 UTC, bauerm97 commented on internal/pkg/build/build.go
> +	// noCleanUp allows a user to prevent a bundle from being cleaned up after a failed build
Same here

2019-03-25 14:56 UTC, bauerm97 commented on internal/pkg/build/build.go
> +	// Options for bundles
And here

2019-03-25 14:56 UTC, bauerm97 commented on internal/pkg/build/build.go
> +	Format string
And here

2019-03-25 14:56 UTC, bauerm97 commented on internal/pkg/build/build.go
> +	Conf Config
```
// Conf [...]
```

2019-03-25 15:21 UTC, bauerm97 approved these changes
I think this looks good for a merge. I do think that for this particular commit (since it's touching a lot of code affecting the build process) we should make sure the integration tests are passing not just the unit tests

2019-03-25 16:28 UTC, merged