Move CLI code to cmd/internal and move application code to internal/app
apptainer/singularity pull request #2532
Opened 2019-01-10 16:52 UTC by bauerm97

**Description of the Pull Request (PR):**

In my ongoing quest to make Singularity code cleaner and a bit more Go idiomatic, I've decided that all code containing the `cobra.Command` structs should live within `cmd/internal/cli`. The reason for that is because we actually have several main packages which need access to those structs:

1. `etc/bash_completion/bash_completion.go`: This file is the main package which uses cobra's bash completion. Since this is actually a main package, we want to put this in the canonical location of `cmd`. Therefore, I've moved it to `cmd/bash_completion/bash_completion.go`.
2. `docs/makeDocs/makeDocs.go`: This file is similar in function to `bash_completion.go`, however it generates man pages instead. I've similarly moved this to `cmd/man_pages/man_pages.go`
3. `cmd/singularity/..`: singularity main cli binary

This PR moves all the CLI code which was previously in `internal/app/singularity` -> `cmd/internal/cli`. Then, I take a first pass at decoupling specific application code from CLI code by moving application code for the `singularity capability ...` command group into `internal/app/singularity`.

@mikegray Can you please take a look at this and make sure I'm not breaking macOS building since I've moved a few files around and added a new one.

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-01-10 17:06 UTC, mikegray reviewed
I pulled the PR locally and it does build successfully on macOS.

2019-01-22 16:54 UTC, ArangoGutierrez requested changes
small tip

2019-01-22 16:54 UTC, ArangoGutierrez commented on cmd/internal/cli/capability.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
Update Copyright -> 2019

2019-01-23 19:24 UTC, ikaneshiro approved these changes
Just a couple nit picks, otherwise LGTM

2019-01-23 19:24 UTC, ikaneshiro commented on cmd/internal/cli/capability_add.go
> +		// manageCap(args[0], capAdd)
I assume this commented code is no longer needed

2019-01-23 19:24 UTC, ikaneshiro commented on cmd/internal/cli/capability_drop.go
> +		// manageCap(args[0], capDrop)
Same as above

2019-01-24 13:22 UTC, tri-adam commented
@bauerm97, LGTM, can you `merge`/`rebase` to resolve the conflicts?

2019-01-25 00:09 UTC, bauerm97 commented
Added a commit updating `pkg/util/capabilities` a bit based on feedback from @tri-adam . New tests have 95% LoC coverage.

2019-01-25 00:09 UTC, ArangoGutierrez commented on pkg/util/capabilities/config.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
2019

2019-01-29 17:50 UTC, bauerm97 commented
Closed and replaced by #2618

2019-01-29 17:50 UTC, closed without merging