Update README.md
apptainer/singularity pull request #2593
Opened 2019-01-23 15:23 UTC by syl-ilumb

Corrected installation options from https://www.sylabs.io/singularity/download/ to https://www.sylabs.io/singularity/ to account for recent updates to the Sylabs.io website.

**Description of the Pull Request (PR):**

Corrected installation options from https://www.sylabs.io/singularity/download/ to https://www.sylabs.io/singularity/ to account for recent updates to the Sylabs.io website.

**This fixes or addresses the following GitHub issues:**

- Fixes #

Incorrect link

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-01-23 15:36 UTC, GodloveD requested changes
I think the link should point here:
https://www.sylabs.io/guides/3.0/user-guide/installation.html

It's probably also useful for members of the open source community to be aware of the PRO offering, so maybe we should explicitly add that as another link as well.

2019-01-23 15:38 UTC, ArangoGutierrez commented on README.md
> +To install Singularity from source, see the [installation instructions](INSTALL.md). For other installation options, see [our website](https://www.sylabs.io/singularity/).
```suggestion
To install Singularity from source, see the [installation instructions](INSTALL.md). For other installation options, see [our website](https://www.sylabs.io/guides/3.0/user-guide/installation.html).
```

2019-01-23 23:24 UTC, ArangoGutierrez approved these changes

2019-01-23 23:37 UTC, ArangoGutierrez commented
PING -> @GodloveD

2019-01-25 02:59 UTC, GodloveD approved these changes

2019-01-25 04:02 UTC, GodloveD commented
Thanks @syl-ilumb and @ArangoGutierrez

2019-01-25 04:02 UTC, merged