makeDocs script improvements
apptainer/singularity pull request #2617
Opened 2019-01-29 06:09 UTC by TMiguelT

**Background**
I'm hoping to get automated CLI documentation into the Singularity docs. Refer to the discussion here: https://github.com/sylabs/singularity-userdocs/issues/73. The first step involved in this is getting Singularity to generate ReST docs that can be consumed by the Sphinx builder in the userdocs repo. I've looked at generating them from that repo, but decided it will be much simpler and cleaner to adapt the existing makeDocs script we have here

**Description of the Pull Request (PR):**
- Convert the makeDocs script to a cobra command
- Allow production of markdown and ReST docs.

**This fixes or addresses the following GitHub issues:**
- This is a step towards https://github.com/sylabs/singularity-userdocs/issues/73

**Before submitting a PR, make sure you have done the following:**

- [x] Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Added tests to validate this PR and tested this PR locally with a `make testall`
- [x] Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- [x] Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-01-29 06:10 UTC, TMiguelT commented
I'm interested in the devs thoughts on:

1) Is the new makeDocs CLI okay (with `the --dir` flag, and no longer defaulting to the man directory)
2) If, where and how I should add tests for this

2019-02-01 06:26 UTC, WestleyK commented on cmd/docs/docs.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
2019?

```suggestion
// Copyright (c) 2019, Sylabs Inc. All rights reserved.
```

2019-02-01 06:41 UTC, jmstover commented on cmd/docs/docs.go
> +// Copyright (c) 2018, Sylabs Inc. All rights reserved.
I agree with the proposed date change here by @WestleyK .

2019-02-01 06:42 UTC, jmstover requested changes
If you can change the copyright date, this looks good to me. Ran it, and output all the different formats.

2019-02-01 07:03 UTC, TMiguelT commented
Does anyone think I need to add tests for this before it gets merged?

2019-02-01 07:13 UTC, jmstover commented
For this... I personally don't think so. This is really pretty self contained.

On a side note, CircleCI failed because of a resource issue.... but I don't have permissions to restart it. If you do a new commit, it should trigger a re-run.

2019-02-01 07:57 UTC, jmstover commented
@TMiguelT ... Thanks. This looks good. Just waiting on the CI to finish up cleanly.

2019-02-01 07:57 UTC, jmstover approved these changes

2019-02-01 15:55 UTC, jchavezlavalle requested changes
Added some comments @TMiguelT thank you!

2019-02-01 15:55 UTC, devprincess commented on cmd/docs/docs.go
> +					sylog.Fatalf("Failed to create markdown docs for singularity\n")
This error warning should be updated to ``Failed to create the ReST format of the docs (or ReST docs) for Singularity``

2019-02-01 15:55 UTC, devprincess commented on cmd/docs/docs.go
> +					sylog.Fatalf("Failed to create man page for singularity\n")
if this works on all man pages then this warning should be in plural: Failed to create **man pages** for Singularity

2019-02-01 16:21 UTC, jscook2345 approved these changes
I approve of this PR, but I will give some feedback on what I may have done differently. Don't feel like you have to make these changes.

I know `ReST` is short for restructured text, but I can't help but think of `REST`. Maybe `RST` would be a better option?

I would of broke each case statement into it's own function for testing purposes. You could than add unit tests (or I can help add them) for each function.

Thanks for your contribution! It's much appreciated!

2019-02-02 01:22 UTC, multimeric commented
Okay, I've fixed the issues that have been mentioned:

- Docs/pages pluralised because in all cases it generates multiple files
- ReST changed to RST for clarity in all cases
- Documentation generation has been split into separate functions
- Fixed the log where I printed "markdown" instead of RST/ReST

In addition, I re-added the directory access check that was in the original script. I suspect that Cobra would tell us if it didn't have access but this might be a more user friendly error

2019-02-02 03:08 UTC, jmstover requested changes

2019-02-02 03:08 UTC, jmstover commented on cmd/docs/docs.go
> +func markdownDocs(out_dir string) {
Can you change `out_dir` to be `outDir`

```
 CHECK go lint
/go/src/github.com/sylabs/singularity/cmd/docs/docs.go:22:19: don't use underscores in Go names; func parameter out_dir should be outDir
```

2019-02-02 03:13 UTC, TMiguelT commented on cmd/docs/docs.go
> +func markdownDocs(out_dir string) {
Done!

2019-02-02 03:33 UTC, jmstover approved these changes

2019-02-02 14:10 UTC, jchavezlavalle approved these changes
lgtm, thanks @TMiguelT !

2019-02-02 15:32 UTC, merged

2019-02-02 15:33 UTC, jmstover commented
Thanks @TMiguelT