Key import command
apptainer/singularity pull request #2781
Opened 2019-02-26 17:06 UTC by devprincess

**Description of the Pull Request (PR):**

This is related to issue #2516 

When using `gpg`, you can export and save one of your generated keys on a local folder with:
```
gpg --export-secret-keys  $KEYID > $HOME/mykey.asc
```
Once saved, you can import this key on your Singularity keystore by using:

`$ singularity key import -path $HOME/mykey.asc` 

This will add the key to the Singularity keystore, this can be checked by running the `singularity key list` command.

**This fixes or addresses the following GitHub issues:**

- Fixes #2516 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-02-26 19:36 UTC, bauerm97 commented
@devprincess Make sure you run `go fmt ./...` with `go1.11` version of `go` installed. `go1.11` has slight formatting differences from `go1.11` and we force `go1.11` formatting. CI should work after that

2019-02-27 00:47 UTC, tri-adam commented
Nice job @devprincess. Some feedback:

Regarding the CLI design, I think it might be more appropriate to use a positional argument for `path`, since it is mandatory:

```sh
$ singularity key import mykey.asc
```

Also, you will need to detect the type of key that is being imported (private vs public) and save it to the appropriate key ring. For example, when I tried this with a private (secret) key:

```sh
$ file my-private-key.asc 
my-private-key.asc: PGP	Secret Key - 4096b created on Tue Apr 24 12:53:26 2018 - RSA (Encrypt or Sign) e=65537 hashed AES with 128-bit key Salted&Iterated S2K SHA-1
```

Importing it added it to the _public_ keys, instead of the private ones:

```sh
$ singularity keys import -path my-private-key.asc 
Key with fingerprint 74D33298DAFF88B7926B7C2BF8C9DE2C26CB1A37 added succesfully to the keystore
$ singularity keys list --secret
Private key listing (/Users/adam/.singularity/sypgp/pgp-secret):

$ singularity keys list 
Public key listing (/Users/adam/.singularity/sypgp/pgp-public):

0) U: Adam Hughes () <stickmanica@gmail.com>
   C: 2018-04-24 12:53:26 -0400 EDT
   F: 74D33298DAFF88B7926B7C2BF8C9DE2C26CB1A37
   L: 4096
   --------
```

2019-03-08 14:26 UTC, mem requested changes

2019-03-08 14:26 UTC, mem commented on cmd/internal/cli/key_import.go
> +	el, err := sypgp.LoadPubKeyring()
Because of the size of this function, I think it's better if you name the variable `el` something else, preferably something that indicates that it refers to the existing keyring.

2019-03-08 14:26 UTC, mem commented on cmd/internal/cli/key_import.go
> +	elstore, err := sypgp.LoadPubKeyringFromFile(path)
and in the same sense, `elstore` should be renamed to something that indicates that this refers to the key being imported (the newly added key).

2019-03-08 14:26 UTC, mem commented on cmd/internal/cli/key_import.go
> +	for _, estore := range elstore {
since `elstore` referes to the new keyring, `estore` refers to one entity in that keyring, right?

2019-03-08 14:26 UTC, mem commented on cmd/internal/cli/key_import.go
> +		for _, e := range el {
and here `el` refers to the existing keyring, and `e` refers to one entity in that keyring.

2019-03-08 14:26 UTC, mem commented on pkg/sypgp/sypgp.go
> +	f, err := os.Open(path)
Please call f.Close()

2019-03-08 14:26 UTC, mem commented on pkg/sypgp/sypgp.go
> +	el, err := openpgp.ReadKeyRing(f)
note that because of the structure of this code, you can change this to:

    return openpgp.ReadKeyRing(f)

2019-03-08 14:26 UTC, mem commented on pkg/sypgp/sypgp.go
>  func LoadPubKeyring() (openpgp.EntityList, error) {
It's probably a good idea that you change the existing `LoadPubKeyring` to call `LoadPubKeyringFromFile(PublicPath())`

2019-03-11 16:39 UTC, devprincess commented
@bauerm97 @tri-adam travis the import command works now but tests from travis are not passing, already updated go to the latest version and also ran `go fmt` what am I missing? thanks in advance!

2019-03-11 16:45 UTC, mem approved these changes
Looks good, thanks!

2019-03-11 18:45 UTC, WestleyK reviewed
This looks really good! I know its a WIP, but heres a couple suggestions.

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +// Copyright (c) 2017-2019, Sylabs Inc. All rights reserved.
I think the going thing is to put the `[year-when-the-file-was-born]-[current-year]`...
Honestly, I prefer to do it like you did, but for consistency, it should probably be like:
```
// Copyright (c) 2019, Sylabs Inc. All rights reserved.
```

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +
I would remove this extra `\n`

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +	//open the file to check if this corresponds to a private or public key
For consistently purposes, I would add a space here:

```suggestion
	// open the file to check if this corresponds to a private or public key
```

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +	//if the block does not correspond to any of public ot private type return error
Here too: 

```suggestion
	// if the block does not correspond to any of public ot private type return error
```

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +	//case on public key import
And here: 

```suggestion
	// case on public key import￼
```

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +		//load the local public keys as entitylist
Well you get the idea...

```suggestion
		// load the local public keys as entitylist
```

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +
Extra `\n`

2019-03-11 18:45 UTC, WestleyK commented on cmd/internal/cli/key_import.go
> +
Here too.

2019-03-11 18:45 UTC, WestleyK commented on docs/content.go
> +	KeyImportUse   string = `import [import options...] -path <full-path-to-local-key>`
`-path`? should it be `--path`?

2019-03-12 20:52 UTC, ikaneshiro approved these changes

2019-03-12 20:59 UTC, merged