Changes to Definition struct to allow section args
apptainer/singularity pull request #3115
Opened 2019-03-25 19:43 UTC by ikaneshiro

**Description of the Pull Request (PR):**

This PR changes many of the fields of the Definition struct in order to encapsulate the idea of a section having additional args. This requires some changes throughout the build package in order to accomodate the change. This also changes the parser to parse those arguements properly into the Definition struct. Also fixes some comments

**This fixes or addresses the following GitHub issues:**

- Fixes #2765 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-03-26 16:00 UTC, WestleyK requested changes
Couple suggestions. Otherwise, looks great!

2019-03-26 16:00 UTC, WestleyK commented on pkg/build/types/definition.go
Copyright for this file should be:

```
// Copyright (c) 2018-2019, Sylabs Inc. All rights reserved.
```

2019-03-26 16:00 UTC, WestleyK commented on pkg/build/types/parser/deffile.go
Copyright for this file should also be:

```
// Copyright (c) 2018-2019, Sylabs Inc. All rights reserved.
```

2019-03-26 16:00 UTC, WestleyK commented on pkg/build/types/parser/deffile.go
>  			//this is a section
I would add a space here, for consistency:

```suggestion
 			// this is a section
```

2019-03-26 16:00 UTC, WestleyK commented on pkg/build/types/parser/deffile_test.go
Copyright for this file should also be:

```
// Copyright (c) 2018-2019, Sylabs Inc. All rights reserved.
```

2019-03-28 22:09 UTC, WestleyK reviewed
Couple more suggestions...

2019-03-28 22:09 UTC, WestleyK commented on internal/pkg/runtime/engines/imgbuild/create_linux.go
>  			sylog.Warningf("Attempt to copy file with no name...")
Is there more to this warning message? I usually use `...` when I want to add something later.

2019-03-28 22:09 UTC, WestleyK commented on internal/pkg/runtime/engines/imgbuild/create_linux.go
On line: `202`, or `209`: return error message should have no caps.

2019-03-28 22:09 UTC, WestleyK commented on pkg/build/types/parser/deffile.go
>  		return fmt.Errorf("Section %v: Could not be split into section name and body", split[0])
Return error should have no caps.

```suggestion
 		return fmt.Errorf("section %v: could not be split into section name and body", split[0])
```

2019-03-28 22:09 UTC, WestleyK commented on pkg/build/types/parser/deffile.go
>  			return fmt.Errorf("App Section %v: Could not be split into section name and app name", sectionSplit[0])
Again, there should be no caps in return error.

```suggestion
 			return fmt.Errorf("app Section %v: could not be split into section name and app name", sectionSplit[0])
```

2019-03-29 15:07 UTC, ikaneshiro commented
Necessary as #3156 will include these changes.

2019-03-29 15:07 UTC, closed without merging