Key export command
apptainer/singularity pull request #3117
Opened 2019-03-25 19:53 UTC by devprincess

**Description of the Pull Request (PR):**

Exporting a key either public or private from the local keystore. 

**This fixes or addresses the following GitHub issues:**

- Fixes #2866 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-03-26 17:24 UTC, mem requested changes

2019-03-26 17:24 UTC, mem commented on cmd/internal/cli/key_export.go
> +	f, err := os.OpenFile(fetchPath, os.O_RDONLY|os.O_CREATE, 0600)
why do you need os.O_CREATE here?

2019-03-26 17:24 UTC, mem commented on cmd/internal/cli/key_export.go
> +	if err := doKeyExportCmd(secretExport, args[0], args[1]); err != nil {
if you pass an io.Writer instead of args[1] here, you can open the file for creation here, and handle the closing. If you don't want to create the file in case of failure, you can still pass an io.Writer (in the form of a bytes.Buffer) that you can later io.Copy into the destination file.

The advantage of this is that you can test the function by passing a bytes.Buffer and comparing the result with the expected result.

2019-03-26 17:24 UTC, mem commented on cmd/internal/cli/key_export.go
> +func doKeyExportCmd(secretExport bool, fingerprint string, path string) error {
I think `path string` should be `w io.Writer` instead, please see below.

2019-03-26 17:24 UTC, mem commented on cmd/internal/cli/key_export.go
> +
I'm guessing somewhere around here you should have a `if !foundKey` to abort if the key is not found.

Up to this point, I would expect the logic to be still shared with the public key path.

2019-03-26 17:24 UTC, mem commented on cmd/internal/cli/key_export.go
> +			err := entityToSave.PrivateKey.Decrypt([]byte(pass))
I'm not 100% sure, but I'm guessing you could postpone asking for the passphrase until this point.

Also, if you use the public keyring, is PrivateKey populated here? I'm trying to figure out if the code path can be shared or not. Could you turn the question of whether you are accessing the public or private keyring into a question of whether the key you retrieved is encrypted or not?

2019-03-26 17:24 UTC, mem commented on docs/content.go
> +	KeyExportUse   string = `export [export options...] <key-fingerprint> <full-path-to-key-file>`
the last argument should be described as "output file" to make it clear that this is the file that will be written.

2019-03-26 17:24 UTC, mem commented on docs/content.go
> +  $ singularity key export --secret <fingerprint_id> <file_folder_path>
same here

2019-03-26 17:24 UTC, mem commented on docs/content.go
> +  $ singularity key export <fingerprint_id> <file_folder_path>
same here

2019-04-09 13:24 UTC, ikaneshiro approved these changes
LGTM

2019-04-09 19:44 UTC, mem approved these changes

2019-04-09 22:26 UTC, merged