[WIP] Revisit sypgp to enable better testing coverage
apptainer/singularity pull request #3165
Opened 2019-03-28 14:00 UTC by gvallee

**Description of the Pull Request (PR):**

Improve testing coverage for sypgp package. Addresses issue #2559

**This fixes or addresses the following GitHub issues:**

- Addresses #2559 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-03-28 14:04 UTC, gvallee commented
This is a set of modifications that improve the testing coverage for the sypgp package.

I would like to have feedback about the changes i did to the package so we can redirect stdin using a file and with that enable automatic testing. I did quite an extensive testing on Linux and did not see any change in the behavior of the various functions of the package.

I also believe others are currently touching PGP support right now so if these modifications are of interest, i have no problem leaving this PR open until all PGP modifications are pushed in; i will update these modifications then.

2019-04-02 07:33 UTC, cclerget requested changes

2019-04-02 07:33 UTC, cclerget commented on pkg/sypgp/sypgp.go
> +	pos, _ := f.Seek(0, os.SEEK_CUR)
If `os.Stdin` is a pipe, seek will fail

2019-04-02 07:33 UTC, cclerget commented on pkg/sypgp/sypgp.go
> +		return
maybe display a warning as we don't return any error here

2019-04-02 07:33 UTC, cclerget commented on pkg/sypgp/sypgp.go
> +		return
safest to return an explicit error message

2019-04-02 07:33 UTC, cclerget commented on pkg/sypgp/sypgp.go
> +		return
same here

2019-04-02 07:33 UTC, cclerget commented on pkg/sypgp/sypgp.go
> +		return nil
should return an error because this is a misuse of this function

2019-04-02 07:33 UTC, cclerget commented on pkg/sypgp/sypgp.go
> +		return nil
same here

2019-04-16 13:41 UTC, gvallee commented
For reference, this work will create major conflicts with #3290

2019-04-24 16:30 UTC, ArangoGutierrez commented
How is this PR going, still a WIP?

2019-04-24 16:41 UTC, gvallee commented
Some work is still ongoing around GPG and signing (mainly #3300) and I do not want to interfere with that work (it is at the point the priority over testing coverage). As soon as it is completed, @mem will merge his work on sygpg.go and then I will merge my work on top of it. So it is almost there, we just need a little more time. :)

2019-06-10 20:56 UTC, gvallee commented
PR #3705 provides a clean PR to introduce the modifications required to handle asking questions in a way that can be automated for testing. It also introduce a few new unit tests for functions that could not be easily tested in the past, based on these modifications.

2019-08-09 13:02 UTC, sashayakovtseva commented
@gvallee Still a WIP or can be closed since #3705 is merged?

2019-08-09 14:35 UTC, closed without merging