Updated Help for 'key' Command
apptainer/singularity pull request #3180
Opened 2019-04-01 20:03 UTC by WestleyK

## Description of the Pull Request (PR):

This PR will update the help output for `singularity key --help`.

## This fixes or addresses the following GitHub issues:

- Fixes #2867 

<br>

2019-04-03 19:04 UTC, jchavezlavalle requested changes

2019-04-03 19:04 UTC, devprincess commented on docs/content.go
> +  Manage OpenPGP keys both locally via a Singluarity keychain
typo on Singularity

2019-04-12 19:37 UTC, GwendolynK-zz requested changes

2019-04-12 19:37 UTC, GwendolynK commented on docs/content.go
> +  default user local keyring location (i.e., $HOME/.singularity/sypgp).`
``` suggestion
  default user's local keyring location (i.e., $HOME/.singularity/sypgp).`
```

2019-04-13 12:56 UTC, jchavezlavalle approved these changes

2019-04-16 18:36 UTC, GwendolynK-zz approved these changes

2019-04-18 21:11 UTC, ikaneshiro approved these changes

2019-04-18 21:37 UTC, merged