Always use gzip for squashfs compression
apptainer/singularity pull request #3215
Opened 2019-04-03 21:23 UTC by ikaneshiro

**This fixes or addresses the following GitHub issues:**

- Fixes #2717 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-04-03 21:43 UTC, WestleyK reviewed
Line: `177`, `172`, `168`, `163`, `159`, `139`, and `118` all have caps in the return error message. I know its outside your changes, but it should probably be fixed. Otherwise, looks good :+1:

2019-04-03 22:38 UTC, ikaneshiro commented
Marking WIP for now since versions of `mksquashfs` less than 4.1 do not have the flag I was using. Will need to add a check.

2019-04-15 16:21 UTC, mem reviewed
LGTM, I haven't approved because it still has the WIP flag, so I don't know if there's pending work?

2019-04-15 18:03 UTC, jmstover commented
This will not work ... See `mksquashfs` on SLES 11
```
# mksquashfs --help 2>&1 | grep 'comp'
-noI                    do not compress inode table
-noD                    do not compress data blocks
-noF                    do not compress fragment blocks
```

There are versions of mksquashfs that do not have the `-comp` flag.

2019-04-15 18:08 UTC, jmstover requested changes

2019-04-15 18:08 UTC, jmstover commented on internal/pkg/build/assemblers/assembler_sif.go
> +	args := []string{b.Rootfs(), squashfsPath, "-noappend", "-comp", "gzip"}
There are versions of mksquashfs on distro's we support that do not have the `-comp` flag

2019-07-02 17:16 UTC, closed without merging