Combine 'apps' With 'inspect'
apptainer/singularity pull request #3390
Opened 2019-04-22 21:59 UTC by WestleyK

## Description of the Pull Request (PR):

This PR will combine `apps` with `inspect`.

## This fixes or addresses the following GitHub issues:

- Fixes #3344 

<br>

2019-04-29 21:53 UTC, mem submitted a review, later dismissed

2019-04-29 21:53 UTC, mem commented on cmd/internal/cli/inspect_linux.go
> +const listAppsCommand = "echo apps:`ls \"$app/scif/apps\" | wc -c`; for app in ${SINGULARITY_MOUNTPOINT}/scif/apps/*; do\n    if [ -d \"$app/scif\" ]; then\n        APPNAME=`basename $app`\n        e
Please add quotes around `$app` when setting APPNAME.
```suggestion
const listAppsCommand = "echo apps:`ls \"$app/scif/apps\" | wc -c`; for app in ${SINGULARITY_MOUNTPOINT}/scif/apps/*; do\n    if [ -d \"$app/scif\" ]; then\n        APPNAME=`basename \"$app\"`\n        echo \"$APPNAME\"\n    fi\ndone\n"
```

2019-05-06 17:33 UTC, ikaneshiro requested changes

2019-05-06 17:33 UTC, ikaneshiro commented on cmd/internal/cli/inspect_linux.go
> +			sylog.Debugf("Inspecting apps in container")
Can we change this to `Inspection of apps selected.` So that all the debug statements are really similar?

2019-05-06 17:33 UTC, ikaneshiro commented on cmd/internal/cli/inspect_linux.go
> +				fmt.Printf("==Apps==\n")
Lets make this `==apps==` for the same reason as above

2019-05-06 18:49 UTC, ikaneshiro approved these changes
lgtm

2019-05-06 18:51 UTC, merged