Create a 'cache' directory after 'SINGULARITY_CACHEDIR' is set
apptainer/singularity pull request #3650
Opened 2019-05-30 17:46 UTC by WestleyK

## Description of the Pull Request (PR):

This PR fixes the issue when you set `SINGULARITY_CACHEDIR` to (for example your home directory `$HOME`), then run `singularity cache clean --all`, not it will not remove your home directory.

This is most likely a temporary fix, until https://github.com/sylabs/singularity/pull/3623 gets merged.

## This fixes or addresses the following GitHub issues:

- Fixes #

<br>

2019-05-30 18:54 UTC, gvallee commented
If I remember correctly, this will cause a failure in `cmd/internal/cli/actions_linux.go` (to be confirmed). The following link may help: https://github.com/sylabs/singularity/pull/3595/files#diff-896d1f4723d0a072f845c405328b7f1e

2019-06-06 17:19 UTC, ikaneshiro approved these changes
lgtm will let @gvallee have a look too before merging

2019-06-06 17:29 UTC, gvallee requested changes
Exactly what I was suggesting, thanks for doing it. I only found a minor typo.

2019-06-06 17:29 UTC, gvallee commented on internal/pkg/client/cache/dir.go
> +		sylog.Debugf("Removeing: %s ...", c)
```suggestion
		sylog.Debugf("Removing: %s ...", c)
```

2019-06-06 18:32 UTC, gvallee approved these changes

2019-06-06 18:53 UTC, merged