Network CNI plugins dependencies update
apptainer/singularity pull request #3771
Opened 2019-06-21 09:05 UTC by cclerget

**Description of the Pull Request (PR):**

This is an attempt to fix an issue when firewall rules are already set (system, docker ...) and conflicts with ones set by CNI plugins

This PR also :
- Updates network CNI plugins dependencies
- Applies changes in network package to use the new API allowing to provide a timeout context for CNI plugins execution
- Updates Singularity network configuration files by adding a new meta plugin `firewall` which will add a forward rule to traffic passthrough between host <=> container

**This fixes or addresses the following GitHub issues:**

- Fixes #3766

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-06-21 12:52 UTC, vsoch commented
Here is a testing of the above PR, first we pull the code here, and install:
```bash
./mconfig 
make -C builddir
cd builddir/
sudo make install
```
Then we create two instances, as previously done

```bash
sudo singularity instance start --net --network-args="IP=10.22.10.10" docker://alpine A
sudo singularity instance start --net --network-args="IP=10.22.10.11" docker://alpine B
sudo singularity exec instance://A ping 10.22.10.11
sudo singularity exec instance://B ping 10.22.10.10
```

And... it works!!! :D :D :D 

https://asciinema.org/a/252939?speed=2

Just curious, are the vendor modules supposed to be served alongside the code, or is this just for testing and the user will install them? I'm going to do the last testing with the singularity-compose-example (with multiple containers) to confirm that everything is good. This one likely will take me a bit longer, so please stay tuned!

2019-06-21 13:17 UTC, cclerget commented
@vsoch Yes, users doesn't need to install them, vendor is provided when you pull a branch or with git archives and network plugins are compiled and installed in one pass

2019-06-21 14:08 UTC, vsoch commented
Okay, working beautifully for the multiple container example! This will fix the issues for any user that has Docker installed, and doesn't have a squeaky clean iptables. I'll add a note to the README that it's recommended to install this branch, given having Docker on the machine.

2019-06-21 14:44 UTC, vsoch commented
Full example (with the PR) is working and ready to go! https://github.com/singularityhub/singularity-compose-example

2019-06-24 19:10 UTC, gvallee requested changes
LGTM, I only suggest a few fixes including a slightly better way to phrase a couple of comments. Feel free to ignore.

2019-06-24 19:10 UTC, gvallee commented on pkg/network/network_linux.go
> +	// provide a timeout context for CNI plugin execution
```suggestion
	// set a timeout context for the execution of the CNI plugin
```

2019-06-24 19:10 UTC, gvallee commented on pkg/network/network_linux.go
> +	// to interrupt the execution if plugins tooks more
```suggestion
	// to interrupt its execution if it takes more than 5 seconds
```

2019-06-24 19:10 UTC, gvallee commented on pkg/network/network_linux.go
> +	// than 5 seconds to do their job
```suggestion
```

2019-07-05 19:08 UTC, WestleyK approved these changes
Looks good to me :+1:

2019-07-08 13:01 UTC, gvallee approved these changes
LGTM!

2019-07-08 13:13 UTC, merged

2019-07-08 21:44 UTC, vsoch commented
Sorry for a late ping on this - I'm finding that using Docker on my machine is totally failing - running containers (on port 3000, for example) with Docker that worked before, many times, are giving me a firewall "This site cannot be reached" error. @cclerget is there anything that was done here to possibly get in the way of Docker working?

2019-07-11 09:42 UTC, cclerget commented
@vsoch I can't figure out how CNI plugins responsible of setting firewall rules prevent docker from working, basically what the plugin does is :

```
iptables -N CNI-FORWARD
iptables -I FORWARD 1 -j CNI-FORWARD
iptables -A CNI-FORWARD -s <container_IP> -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A CNI-FORWARD -d <container_IP> -j ACCEPT
```

* `iptables -N CNI-FORWARD`: it creates a user defined chain `CNI-FORWARD`
* `iptables -I FORWARD 1 -j CNI-FORWARD`: insert a rule in the chain `FORWARD` (docker has a similar chain called `DOCKER-ISOLATION` or something like that) so all packet will go through `CNI-FORWARD` user defined chain to be checked against rules below
* `iptables -A CNI-FORWARD -s <container_IP> -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT`: allow traffic forwarding from the container to host
* `iptables -A CNI-FORWARD -d <container_IP> -j ACCEPT`: allow traffic forwarding from host to the container

Just to confirm I read this https://netfilter.org/documentation/HOWTO/packet-filtering-HOWTO-7.html#ss7.4, so when docker firewall are set, forwarded packets will go first through `CNI-FORWARD`, if those packets come from/go to a singularity container, they are flagged as accepted, if the packets come from/go to a docker container, they should just be ignored by `CNI-FORWARD` rules and continue to go through next rules in `FORWARD` chains, logically the next user defined chain in `FORWARD` is `DOCKER-ISOLATION`, so those packets should find a docker rule in `DOCKER-ISOLATION` chain accepting them.

Do you run Singularity and Docker containers in the same network address space ?

2019-07-11 12:49 UTC, vsoch commented
hey @cclerget ! I'm not sure what the issue was, but I wound up deleting and reinstalling docker (and all seems to be working). I haven't tested Singularity again but let's just be optimistic and (based on the logic above) say that all is well! Thanks for the detailed debugging. :)