e2e tests for OCI commands
apptainer/singularity pull request #3893
Opened 2019-07-09 11:57 UTC by cclerget

**Description of the Pull Request (PR):**

Title

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-07-12 13:26 UTC, gvallee requested changes
Only minor comments...

2019-07-12 13:26 UTC, gvallee commented on e2e/oci/oci.go
> +		// due to command Wait call waiting that executed command
```suggestion
		// due to command Wait call that waits for the execution of a command
```

2019-07-12 13:26 UTC, gvallee commented on e2e/oci/oci.go
> +		// close standard file descriptor, but OCI create keep
```suggestion
		//  that closes standard file descriptors, but OCI create keeps
```

2019-07-12 13:26 UTC, gvallee commented on e2e/oci/oci.go
> +		// this is required otherwise oci create hangs, this is
Maybe update the comment like above

2019-07-12 16:42 UTC, cclerget commented on e2e/oci/oci.go
> +		// this is required otherwise oci create hangs, this is
Will do, thanks !

2019-07-15 14:35 UTC, gvallee approved these changes
LGTM

2019-07-15 14:36 UTC, merged