e2e port tests related to help cmd
apptainer/singularity pull request #3924
Opened 2019-07-12 13:28 UTC by devprincess

**Description of the Pull Request (PR):**

Port help command tests with the new execution context.

**This fixes or addresses the following GitHub issues:**

- Fixes https://github.com/sylabs/singularity/issues/3831

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-07-12 14:48 UTC, jscook2345 commented on e2e/help/help.go
>  		{"Bootstrap", []string{"bootstrap"}},
I don't think there is a bootstrap command anymore

2019-07-12 15:31 UTC, cclerget requested changes

2019-07-12 15:31 UTC, cclerget commented on e2e/help/help.go
> +	{"HelpOci", []string{"help", "oci"}},
you could get rid of `"help"` for all lines, and use `WithCommand("help"), WithArgs(tc.cmds...)` around https://github.com/sylabs/singularity/pull/3924/files#diff-2f7903baca57c225790dd52d14e1162eR60

2019-07-12 15:31 UTC, cclerget commented on e2e/help/help.go
>  		argv []string
For readability, you could replace `argv []string` by `cmd string`, pass the `cmd` argument directly to `WithCommand(tt.cmd)` here https://github.com/sylabs/singularity/pull/3924/files#diff-2f7903baca57c225790dd52d14e1162eR115 and remove `WithArgs` (`WithCommand` split string argument by space so it's fine with `"instance start"` as command by example).
Then you could reuse `WithCommand(tt.cmd)` in `testCmdsFn` in conjunction with `WithArgs(tf.argv...)`

2019-07-12 15:31 UTC, cclerget commented on e2e/help/help.go
>  		t.Run(tt.name, func(t *testing.T) {
`t.Run` call can be removed

2019-07-12 15:31 UTC, cclerget commented on e2e/help/help.go
> +			e2e.PostRun(func(t *testing.T) {
no need to call `PostRun` and checks, `ExpectExit` can take care of that, you just need to replace `shouldPass bool` at https://github.com/sylabs/singularity/blob/4e794e3b0c283d88558e160a7b790553d655d319/e2e/help/help.go#L169
 by `exit int` to provide the expected exit code

2019-07-15 08:04 UTC, cclerget requested changes

2019-07-15 08:04 UTC, cclerget commented on e2e/help/help.go
> +		{"NoCommand", []string{}, 0},
```suggestion
		{"NoCommand", []string{}, 1},
```

2019-07-15 08:04 UTC, cclerget commented on e2e/help/help.go
> +		{"FlagShort", []string{"-h"}, 1},
```suggestion
		{"FlagShort", []string{"-h"}, 0},
```

2019-07-15 08:04 UTC, cclerget commented on e2e/help/help.go
> +		{"FlagLong", []string{"--help"}, 1},
```suggestion
		{"FlagLong", []string{"--help"}, 0},
```

2019-07-15 08:04 UTC, cclerget commented on e2e/help/help.go
> +		{"Command", []string{"help"}, 1},
```suggestion
		{"Command", []string{"help"}, 0},
```

2019-07-15 08:04 UTC, cclerget commented on e2e/help/help.go
> +				t.Skip("disabled until issue addressed")
if `t.Skip` is called here it will skip the entire `testCommands` suite, need to be part of a `PreRun` call within `e2e.RunSingularity`

2019-07-15 08:04 UTC, cclerget commented on e2e/help/help.go
> +		testFlags := []struct {
```suggestion
		testFlags := []struct {
			name string
			argv string
			skip bool
		}{
			{"PostFlagShort", append(tt.cmd, "-h"), true}, // TODO
			{"PostFlagLong", append(tt.cmd, "--help"), false},
			{"PostCommand", append(tt.cmd, "help"), false},
			{"PreFlagShort", append([]string{"-h"}, tt.cmd...), false},
			{"PreFlagLong", append([]string{"--help"}, tt.cmd...), false},
			{"PreCommand", append([]string{"help"}, tt.cmd...), false},
		}
```

2019-07-15 08:04 UTC, cclerget commented on e2e/help/help.go
> +			e2e.RunSingularity(t, tf.name, e2e.WithCommand(tt.cmd), e2e.WithArgs(tf.argv),
```suggestion
			e2e.RunSingularity(t, tf.name, e2e.WithArgs(tf.argv),
```

2019-07-18 09:48 UTC, cclerget approved these changes

2019-07-18 13:53 UTC, gvallee approved these changes
LGTM

2019-07-19 07:53 UTC, merged