Lock ext3 image partitions and prevent them from concurrent writes
apptainer/singularity pull request #4069
Opened 2019-08-01 12:56 UTC by cclerget

**Description of the Pull Request (PR):**

Lock EXT3 image partitions to prevent from concurrent writes

**This fixes or addresses the following GitHub issues:**

- Fixes #4048 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-08-21 15:51 UTC, mem commented on internal/pkg/runtime/engines/singularity/prepare_linux.go
> +						return fmt.Errorf("error while loading ext3 overlay partition from %s: %s", img.Path, err)
"while locking", no?

2019-08-21 15:51 UTC, mem commented on internal/pkg/runtime/engines/singularity/prepare_linux.go
> +		// or check if the image is not already opened for writing
not sure where the "or" part of this comment is...

Is `LockSection` doing something more than just locking?

2019-08-21 15:51 UTC, mem commented on internal/pkg/runtime/engines/singularity/prepare_linux.go
> +			return fmt.Errorf("error while loading ext3 system partition from %s: %s", img.Path, err)
"while locking"?

2019-08-21 15:51 UTC, mem commented on internal/pkg/runtime/engines/singularity/prepare_linux.go
> +				return fmt.Errorf("error while loading ext3 overlay image %s: %s", img.Path, err)
"while locking"?

2019-08-21 15:51 UTC, mem commented on pkg/image/image.go
> +// LockSection put a file byte-range lock on a section to prevent
"LockSection puts ..."

2019-08-21 15:51 UTC, mem commented on pkg/image/image.go
> +	} else if err != nil {
Not sure what to do with this...

The function is supposed to acquire a lock, fails to do so and no error is reported. I understand the need to support filesystems where locking is not available, but I don't think dropping all errors is the right way to go about it.

Ideally it should not be necessary to dig into the implementation details to understand the logic. I suspect this handling of errors is tightly related to implementation details.

2019-08-21 15:51 UTC, mem commented on pkg/image/image.go
> +	if err := br.Acquire(ltype); err == lock.ErrByteRangeAcquired {
as a general comment, looking at the implementation of these functions (Acquire, etc), I think the client code would be easier to read if you had a different API. Instead of having a parameter specifying the type of lock, something more like:

```
func (ByteRange) RLock()
func (ByteRange) Lock()
func (ByteRange) Unlock()
```

If you look at the sync package, you'll see that read vs read-write is handled at the type level: you create a read lock, you create a rw lock.

2019-08-21 15:51 UTC, mem commented on pkg/util/fs/lock/lock.go
> +type Type uint8
this type and the corresponding constants are mimicking the underlying flock API. I don't think these are necessary (or at least, I don't think it's necessary to export these; obviously it's necessary with the current implementation).

2019-08-21 15:51 UTC, mem commented on pkg/util/fs/lock/lock.go
> +type ByteRange struct {
`ByteRangeLock` maybe? I don't really like it because it stutters with the package name (lock.ByteRangeLock). The standard library side-stepped this problem by calling the somewhat equivalent package `sync`, so it results in `sync.Mutex`, etc.

Within the package the problem I see with `ByteRange` is that it sounds like it's something else (something representing a byte range, not a lock on a byte range).

2019-08-21 18:31 UTC, cclerget commented on pkg/image/image.go
> +	} else if err != nil {
Will just ignore `ENOLCK` error and will see if it block users

2019-08-21 18:31 UTC, cclerget commented on pkg/image/image.go
> +	if err := br.Acquire(ltype); err == lock.ErrByteRangeAcquired {
will do, thanks !

2019-08-21 18:33 UTC, cclerget commented on pkg/util/fs/lock/lock.go
> +type ByteRange struct {
Well we are in package `lock` and get `lock.ByteRange`, that's explicit enough at least for me and there is many package with this kind of "shortcuted" name

2019-08-26 12:53 UTC, sashayakovtseva commented on pkg/util/fs/lock/lock.go
> +// ErrByteRangeAcquired correponds to the error returned
```suggestion
// ErrByteRangeAcquired corresponds to the error returned
```

2019-08-26 12:53 UTC, sashayakovtseva commented on pkg/util/fs/lock/lock.go
> +// when a file byte-range is already acquired
```suggestion
// when a file byte-range is already acquired.
```

2019-08-26 13:47 UTC, sashayakovtseva requested changes
lgtm
as discussed offline a couple things to address:
- ErrLockNotSupported
- lock partition[0] of SIF if it is ext3 (even though it is a rare case)
- F_SETLK64 is equal to F_SETLK in linux, so probably no need to separate const and const_linux

2019-08-26 14:52 UTC, sashayakovtseva approved these changes
lgtm

2019-08-27 07:45 UTC, merged