Ensure image permission of 777 when overriding the image
apptainer/singularity pull request #4196
Opened 2019-08-14 01:00 UTC by WestleyK

## Description of the Pull Request (PR):

This PR ensures that the image file permission is 777 when overriding the file.

### This fixes or addresses the following GitHub issues:

- Fixes #4177

<br>

2019-08-14 01:40 UTC, gvallee approved these changes
lgtm

2019-08-14 01:57 UTC, jmstover requested changes
Don't set permission to `0777` ... World/Group writable not good.

2019-08-14 01:57 UTC, jmstover commented on internal/pkg/library/library.go
> +	err = destFile.Chmod(0777)
Change this to `destFile.Chmod(0755)` ...

2019-08-14 02:18 UTC, jmstover commented on internal/pkg/library/library.go
> +	err = destFile.Chmod(0777)
Also ... this looks like it's going to override the users `umask` setting... Is that correct?

2019-08-15 19:49 UTC, jmstover approved these changes

2019-08-15 22:13 UTC, ikaneshiro approved these changes

2019-08-15 22:35 UTC, merged