Improve e2e coverage for the key command
apptainer/singularity pull request #4307
Opened 2019-08-23 20:30 UTC by gvallee

**Description of the Pull Request (PR):**

Improve e2e coverage for the key command:
- add a few tests for `singularity key <subcmd> --help` commands
- add tests for `singularity key newpair --but-length` commands

**This fixes or addresses the following GitHub issues:**

- Addresses #4087 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-08-27 01:49 UTC, WestleyK requested changes
Thanks for improving this, just a couple suggestions :+1:

2019-08-27 01:49 UTC, WestleyK commented on e2e/key/key.go
> +		c.singularityResetKeyring(t) // Remove the tmp keyring before each import
You dont need this line here.

```suggestion
```

2019-08-27 01:49 UTC, WestleyK commented on e2e/key/key.go
> +			name:          "help",
Just to make it a little more clear

```suggestion
￼			name:          "push help",
```

2019-08-27 01:49 UTC, WestleyK commented on e2e/key/key.go
> +		c.singularityResetKeyring(t) // Remove the tmp keyring before each import
Same here.

```suggestion
```

2019-08-27 01:49 UTC, WestleyK commented on e2e/key/key.go
> +			name:          "help",
```suggestion
			name:          "pull help",
```

2019-08-27 01:49 UTC, WestleyK commented on e2e/key/key.go
> +			name:          "help",
```suggestion
			name:          "remove help",
```

2019-08-27 01:49 UTC, WestleyK commented on e2e/key/key.go
> +		c.singularityResetKeyring(t) // Remove the tmp keyring before each import
Same here.

```suggestion
```

2019-08-27 01:49 UTC, WestleyK commented on e2e/key/key.go
> +			expectedKeyLength: 2048,
Why do you expect 2048 here?

2019-08-28 19:32 UTC, gvallee commented on e2e/key/key.go
> +			expectedKeyLength: 2048,
@WestleyK as far as I can tell it is the default size and what I get when running the test :)

2019-08-29 15:24 UTC, WestleyK approved these changes
Looks good to me! Thanks :+1:

2019-08-29 21:26 UTC, merged