Clean up abandoned files in /tmp
apptainer/singularity pull request #4317
Opened 2019-08-27 22:01 UTC by ikaneshiro

These changes are only within the context of unit tests with the
exception of a change to the SIF assembler to clean up a left over file
from building encrypted containers.

Signed-off-by: Ian Kaneshiro <iankane@umich.edu>

**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Fixes #

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-08-27 22:12 UTC, mem approved these changes
thanks

2019-08-28 14:55 UTC, gvallee requested changes
Only a minor comment

2019-08-28 14:55 UTC, gvallee commented on internal/pkg/build/files/copy_test.go
> +			path := dir + "/" + tt.path
maybe use `filepath.Join()` here?

2019-08-28 14:59 UTC, ikaneshiro commented on internal/pkg/build/files/copy_test.go
> +			path := dir + "/" + tt.path
`filepath.Join()` will remove trailing `/` from paths which are a significant component to paths for this function as it follows the convention of `cp` assuming that paths ending with a slash are directories.

2019-08-28 18:12 UTC, gvallee approved these changes
lgtm

2019-08-28 18:12 UTC, gvallee commented on internal/pkg/build/files/copy_test.go
> +			path := dir + "/" + tt.path
Sorry I missed the comment.

2019-08-28 19:54 UTC, merged