Preserve parent OCI config
apptainer/singularity pull request #4422
Opened 2019-09-12 13:17 UTC by sashayakovtseva

**Description of the Pull Request (PR):**

In order to preserve parent's OCI config SIF packer now stores it (if any) into a bundle's JSON objects map.

Also minor changes:
- add a constant for oci config JSON object 
- change methods to functions where receiver is not used
- use sif magic as defined in sif package
- use nil slice instead of `[]string{}` in squashfs extractor
- remove redundant uint64 conversion
- do not check rootfs descriptor datatype b/c it is already checked in the next called function
- use camelCase/common names where possible
- add periods in godoc comments

**This fixes or addresses the following GitHub issues:**

- Fixes #4415 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-09-12 15:25 UTC, cclerget requested changes

2019-09-12 15:25 UTC, cclerget commented on internal/pkg/build/sources/packer_sif_linux.go
> +	if err != nil && err != image.ErrNoSection {
Maybe something like :

```
	if err == image.ErrNoSection {
                sylog.Debugf("No oci-config.json section found")
        } else if err != nil {
                return fmt.Errorf("could not read image OCI config: %v", err)
	} else {
                ociConfig, err := ioutil.ReadAll(ociReader)
                ...
        }
```

Other errors returned by `NewSectionReader` are fatal in this case

2019-09-12 15:25 UTC, cclerget commented on pkg/image/sif.go
> -		if desc.Datatype != sif.DataPartition {
What the reason behind this removal ?

2019-09-12 15:26 UTC, sashayakovtseva commented on pkg/image/sif.go
> -		if desc.Datatype != sif.DataPartition {
The next call to `desc.GetPartType()` already does this check:

```

// GetPartType extracts the Parttype field from the Extra field of a Partition Descriptor
func (descr *Descriptor) GetPartType() (Parttype, error) {
	if descr.Datatype != DataPartition {
		return -1, fmt.Errorf("expected DataPartition, got %v", descr.Datatype)
	}
...
```

2019-09-12 15:31 UTC, sashayakovtseva commented on internal/pkg/build/sources/packer_sif_linux.go
> +	if err != nil && err != image.ErrNoSection {
I thought we might want to count those error as non fatal, but now I think that this mean SIF is corrupted. Agree, thanks.

2019-09-12 15:35 UTC, mem approved these changes

2019-09-12 18:19 UTC, ikaneshiro approved these changes
lgtm, thanks

2019-09-13 08:22 UTC, cclerget approved these changes

2019-09-13 09:38 UTC, merged