Cleanup overlay e2e actions test
apptainer/singularity pull request #4514
Opened 2019-09-24 15:17 UTC by cclerget

## Description of the Pull Request (PR):

- Add `overlay` filesystem requirement and required command to execute tests
- Use `fs.Touch` to cleanup a bit

- Fixes #4513 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2019-09-24 15:28 UTC, sashayakovtseva approved these changes

2019-09-24 16:05 UTC, mem commented on e2e/actions/actions.go
> +	squashfsImage := filepath.Join(c.env.TestDir, "squashfs.simg")
Since these are being created (the squashfs image, the ext3 image, the sandbox directory) they should either be created in their own unique directory or they should be given unique names.

The fact that they are removed after this runs (e.g. line 696 below) means they are transient artifacts for this test, so making sure they are specific to this test is important. Assuming c.env.TestDir is going to be unique is not enough, and it would be really helpful for readability to *NOT* introduce magic to make that assumption valid.

Creating a unique directory for the test is the easiest option. Something as simple as:

```
testdir := ioutil.TempDir(c.env.TestDir, "persistent-overlay.")

defer func(t *testing.T) {
    if t.Failed() {
        t.Logf("Not removing directory %s for test %s", testdir, t.Name())
        return
    }
    err := os.RemoveAll(testdir)
    if err != nil {
        t.Logf("Error while removing directory %s for test %s: %#v", testdir, t.Name(), err)
    }
}(t)

squashfsImage := filepath.Join(testdir, "squashfs.img")
ext3Image := filepath.Join(testdir, "ext3.img")
sandboxImage := filepath.Join(testdir, "sandbox")
```

2019-09-24 16:05 UTC, mem commented on e2e/actions/actions.go
> +	dir, err := ioutil.TempDir(c.env.TestDir, "overlay-dir")
same idea here, this should be created in `testdir` from the previous comment.

Also, it would be nice to add a separator at the end of the prefix argument to `TempDir`, as this results in names that look like "/tmp/overlay-dir783889482". Adding the separator gives you "/tmp/overlay-dir.783889482" which makes it easier to read in logs and elsewhere.

2019-09-24 16:05 UTC, mem commented on e2e/actions/actions.go
>  	defer os.RemoveAll(dir)
if you create everything inside a test-specific directory, you don't need to clean up all the items one by one.

2019-09-24 16:05 UTC, mem commented on e2e/actions/actions.go
> +	squashDir, err := ioutil.TempDir(c.env.TestDir, "root-squash-dir")
same here

2019-09-24 16:05 UTC, mem commented on e2e/actions/actions.go
> +	bogusFile := "bogus"
skimming thru the test of the code here, there doesn't seem to be anything bogus about this file. It looks like it's just a temporary file to provide content for the image.

For readability's sake, please consider changing the name of the file and the name of the variable.

If the file is indeed bogus in some sense, please consider adding a comment explaining what's special about it or what this is trying to test.

2019-09-24 16:05 UTC, mem commented on e2e/actions/actions.go
> +	cmd = exec.Command("dd", "if=/dev/zero", "of="+ext3Img, "bs=1M", "count=64", "status=none")
thanks for making this smaller.

2019-09-24 16:05 UTC, mem requested changes
sorry, I would like to see these comments addressed

2019-09-26 22:27 UTC, mem approved these changes
thanks!

2019-09-27 14:40 UTC, merged