Add global keyring management for ECL
apptainer/singularity pull request #5637
Opened 2020-10-20 14:44 UTC by cclerget

## Description of the Pull Request (PR):

Add a `--global` flag for  `key import/export/list/pull/push/remove` commands to manage the global keyring stored at `SYSCONFDIR/singularity/pgp-public`.

ECL now exclusively use the global keyring.  Global keyring is also used by `singularity verify` with an explicit tag `[GLOBAL]`

### This fixes or addresses the following GitHub issues:

 - Fixes #5613

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2020-10-21 20:17 UTC, dctrud commented
Hi @cclerget - as this is a fairly big one I'll block out a chunk of time I can go through it properly Thursday or Friday. I've asked @tri-adam to take a look early next week if he can as he's pretty familiar with the ECL stuff from the sign/verify security rework.

2020-10-22 20:08 UTC, dctrud requested changes
Looks reasonable to me. I left a few minor comments.

Things I do think are important:

- This code doesn't check that the global keyring is owned by root when ECL is in use. This is inconsistent with the fact that we *do* check the ecl config is owned by root:

```
03:03 PM $ singularity run alpine_latest.sif 
Singularity>

# Still runs with pgp-public owned by me
03:03 PM $ sudo chown dave.dave /usr/local/etc/singularity/pgp-public
03:04 PM $ singularity run alpine_latest.sif 
Singularity> 

# But not if ecl.toml is owned by me
03:04 PM $ sudo chown dave.dave /usr/local/etc/singularity/ecl.toml 
03:04 PM $ singularity run alpine_latest.sif 
FATAL:   /usr/local/etc/singularity/ecl.toml must be owned by root
```

- `docs/content.go` needs to be updated for the key command / subcommands. At present it does not mention the global keyring, and explicitly gives the path to the user keyring etc.

- An issue must be added to the userdocs and admindocs repo, to update for these changes. They need to be blockers for release of 3.7.

2020-10-22 20:08 UTC, dtrudg commented on cmd/internal/cli/key.go
> +	Usage:        "use global public keys (import/pull/remove are restricted to root user or unprivileged installation only)",
```suggestion
	Usage:        "manage global public keys (import/pull/remove are restricted to root user or unprivileged installation only)",
```

2020-10-22 20:08 UTC, dtrudg commented on dist/rpm/singularity.spec.in
> +%config(noreplace) %{_sysconfdir}/singularity/pgp-public
I'd probably call this `global-pgp-public` just so it includes the word `global` which is throughout the UI now.

2020-10-22 20:08 UTC, dtrudg commented on e2e/ecl/ecl.go
> +func (c *ctx) eclConfig(t *testing.T) {
In these tests it seems a little odd to be running our own builds etc. when we have test images and keys in `singularity/internal/pkg/syecl/testdata` - I'm just wondering if there is a way to unify the ecl testing a bit so we don't have multiple places to update?

2020-10-22 20:08 UTC, dtrudg commented on mlocal/frags/build_runtime.mk
> +global_keyring := $(SOURCEDIR)/etc/pgp-public
See other comment - I think global-pgp-public is better to match the 'global' throughout the ui

2020-10-26 10:16 UTC, cclerget commented on e2e/ecl/ecl.go
> +func (c *ctx) eclConfig(t *testing.T) {
Well images in this package are running only on x86 platforms and e2e tests need full execution contrary to syecl package, I'm not sure about e2e tests if busybox is supported for different platforms as tests uses library ... and with docker rate limit coming soon. A clear separation between integration/unit tests and e2e tests regarding test data is good imo and eventually allow to spot different bugs.

2020-10-26 13:30 UTC, dctrud commented on e2e/ecl/ecl.go
> +func (c *ctx) eclConfig(t *testing.T) {
okay, fair enough.

2020-10-26 13:31 UTC, dctrud approved these changes

2020-10-26 13:34 UTC, tri-adam commented
The code looks good to me. Only real issue I can see is that the documentation talks about managing global public keys, but the `--secret` flag can be used in combination with `--global`? I'm not sure this is intentional? For example:

```sh
$ singularity key list --global --secret
Private key listing (/usr/local/etc/singularity/pgp-secret)
```

2020-10-26 15:11 UTC, cclerget commented
@tri-adam Fixed, checks regarding private keys are done in sypgp package, but `key list` didn't checked errors from calls `PrintPubKeyring` and `PrintPrivKeyring`

2020-10-26 17:27 UTC, dctrud approved these changes
LGTM for ad's comment

2020-10-26 17:27 UTC, merged