Use MaxLoopDevices variable from config file
apptainer/singularity pull request #5660
Opened 2020-10-26 21:08 UTC by locula

## Description of the Pull Request (PR):

This PR makes use of the MaxLoopDevices variable defined in the config file in all the places where the maximum number of loop devices is referenced. This makes it easy for users to change this value as they choose.

### This fixes or addresses the following GitHub issues:

 - Addresses #5614

2020-11-05 21:03 UTC, dctrud requested changes

2020-11-05 21:03 UTC, dctrud commented on pkg/util/loop/loop_linux_test.go
> +func getMaxLoopDevices() int {
This `getMaxLoopDevices` is repeated in many locations - please instead define it once as an exported/Public function (probably in `pkg/util/loop` is a good place - and then call it from other places it is needed.

2020-11-05 21:03 UTC, dctrud commented on pkg/util/crypt/crypt_dev.go
> +func getMaxLoopDevices() int {
This `getMaxLoopDevices` is repeated in many locations - please instead define it once as an exported/Public function (probably in `pkg/util/loop` is a good place - and then call it from other places it is needed.

2020-11-05 21:03 UTC, dctrud commented on pkg/ocibundle/tools/loop.go
> +func getMaxLoopDevices() int {
This `getMaxLoopDevices` is repeated in many locations - please instead define it once as an exported/Public function (probably in `pkg/util/loop` is a good place - and then call it from other places it is needed.

2020-11-05 21:03 UTC, dctrud commented on internal/pkg/build/sources/packer_ext3_linux.go
> +func getMaxLoopDevices() int {
This `getMaxLoopDevices` is repeated in many locations - please instead define it once as an exported/Public function (probably in `pkg/util/loop` is a good place - and then call it from other places it is needed.

2020-11-06 16:45 UTC, dctrud commented
@cclerget - do you have any input on this? The general intent seems fine to me. However it does introduce the issue that things in `pkg/xxx` no depend on the `internal/pkg` config handling - so they aren't really independent of a Singularity install.

I think we probably need to look at how stuff could be shuffled around to avoid this hard `internal/` dep from `pkg/` if at all possible? I know we have #2316 which has been open for a long time to address this, and would hope we can make progress there rather than steps back.

2020-11-09 14:39 UTC, cclerget commented
@dctrud @locula In order to deal with `buildcfg` dependency from a public package, the easiest approach is to create two files in `pkg/loop` and use go build tags :

- loop_singularity.go

```
// +build singularity_engine

package loop

import (
	"github.com/sylabs/singularity/internal/pkg/buildcfg"
	"github.com/sylabs/singularity/pkg/util/singularityconf"
)

func GetMaxLoopDevices() int {
	// if the caller has set the current config use it
	// otherwise parse the default configuration file
	cfg := singularityconf.GetCurrentConfig()
	if cfg == nil {
		var err error

		configFile := buildcfg.SINGULARITY_CONF_FILE
		cfg, err = singularityconf.Parse(configFile)
		if err != nil {
			return 256
		}
	}
	return int(cfg.MaxLoopDevices)
}
```

- loop_no_singularity.go

```
// +build !singularity_engine

package loop

func GetMaxLoopDevices() int {
        // externally imported package, use the default value
	return 256
}
```

This way external project would use `loop_no_singularity.go`.

> I think we probably need to look at how stuff could be shuffled around to avoid this hard internal/ dep from pkg/ if at all possible? I know we have #2316 which has been open for a long time to address this, and would hope we can make progress there rather than steps back.

Currently two packages are using `buildcfg` as indirect dependency: `pkg/build/types` and `pkg/util/crypt` and would require some modification before adding this check

2020-11-09 14:41 UTC, cclerget requested changes
Require to manage `buildcfg` internal dependency as described in https://github.com/hpcng/singularity/pull/5660#issuecomment-724054468

2020-11-23 21:57 UTC, locula commented
@dctrud I've removed the internal dependencies and updated the code. Is there any additional feedback for this?

2020-11-23 22:19 UTC, dctrud commented
@locula - we'll come back to this soon after the 3.7.0 release. I'm afraid things are a bit busy in that regard at present.

2020-12-14 18:25 UTC, locula commented
Hi, I just wanted to follow up and check if there are any updates on this.

2020-12-16 15:30 UTC, cclerget approved these changes
LGTM, thanks @locula ! And sorry for the delay

2020-12-16 18:44 UTC, dctrud approved these changes

2020-12-16 18:44 UTC, merged