WIP - Allow specified non-root users/groups to use --net
apptainer/singularity pull request #5886
Opened 2021-03-22 20:21 UTC by dtrudg

Work In Progress, draft PR

## Description of the Pull Request (PR):

Currently....

- Add `allow net users` and `allow net groups` directives to `singularity.conf`.
- Users or groups specified here can use any CNI conflist in the admin configured `/etc/singularity/network` directory.

This doesn't exactly match the proposal in #5828 where it was said we would restrict specific users/groups to *specific configs*. Currently looking into whether the simpler approach of 'bless a user/group for all configs' is sufficient for users who've expressed an interest in this.

May end up adding another directive to list the CNI conflists that are premitted to these users.

### This fixes or addresses the following GitHub issues:

 - Fixes #5828

2021-03-24 13:36 UTC, EmmEff approved these changes, later dismissed
Looks good to me

2021-03-24 14:02 UTC, dtrudg commented
Thanks for the review @EmmEff - as this is a new feature providing a way to open stuff up a bit I'll leave it for a while so hopefully @cclerget or @ikaneshiro can take a look also.

2021-04-08 09:04 UTC, cclerget requested changes
Base on requested changes, it would also be useful to test e2e cases around multiple networks both on user and admin side

2021-04-08 09:04 UTC, cclerget commented on internal/pkg/runtime/engine/singularity/container_linux.go
> +		allowedNetNetwork := slice.ContainsString(c.engine.EngineConfig.File.AllowNetNetworks, net)
`c.engine.EngineConfig.GetNetwork()` can return a comma separated string list of networks, it was fine for fakeroot and none network type because it didn't make sense to specify multiple network type in those cases but now that multiple network can be specified by users, the `networks` variable https://github.com/hpcng/singularity/pull/5886/files#diff-f67e2c208cc91cfb48a661272eadb404f0dd544cbe36fe77ec0d2af46aad8543R2282 must be used here

2021-04-08 09:04 UTC, cclerget commented on internal/pkg/runtime/engine/singularity/container_linux.go
> +			if err := networkSetup.SetPortProtection(net, 0); err != nil {
And loop over networks here

2021-04-08 20:03 UTC, dtrudg commented
@cclerget - thanks for feedback. Should accommodate the multiple networks now.

2021-04-09 07:41 UTC, cclerget approved these changes
LGTM

2021-04-09 13:31 UTC, merged