Add overlay command to ease the creation of ext3 writable overlay
apptainer/singularity pull request #5913
Opened 2021-04-09 13:35 UTC by cclerget

## Description of the Pull Request (PR):

Add overlay command to ease the creation of ext3 writable overlay
- allow to create an overlay as a single ext3 image file.
- allow to create and add an ext3 writable overlay to an existing SIF image.

SIF restrictions:
- SIF image must not contain a writable overlay
- SIF image must not be signed

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

2021-04-09 13:54 UTC, dtrudg commented
Hi @cclerget - I'll probably get around to a proper review on Monday.

A quick thought though...

> SIF restrictions:
> 
>     * SIF image must not contain a writable overlay
> 
>     * SIF image must not be signed

Should there be some restriction or warning for SIFs where the rootfs is encrypted? Our overlay will not be, and that may not be intuitive / expected to the user?

2021-04-09 13:59 UTC, cclerget commented
Ah right forgot encryption case, thanks !

2021-04-12 21:49 UTC, dtrudg requested changes
Looks mostly good to me. A few minor docs / messages things commented here.

Couple of questions....

- Why not e.g. `truncate --size 1024M myfile` instead of `dd` as that will be faster and less likely to exhaust disk as it creates a sparse file?
- `mkfs.ext3` is not in the standard user PATH on at least debian 10+, as that doesn't include`/sbin`. Worth looking in `/sbin` by default?

2021-04-12 21:49 UTC, dtrudg commented on cmd/internal/cli/overlay_create.go
> +	Usage:        "size of the EXT3 writable overlay in MB",
Presumably this is MiB? If so can we put MiB here as we have had some confusion previously with powers of 10 MB vs powers of 2 MiB in some code.

2021-04-12 21:49 UTC, dtrudg commented on docs/content.go
> +	OverlayShort string = `Manage EXT3 writable overlay image`
Either 'Manage **an** EXT3 image....' or ' Manage..... image**s**'

2021-04-12 21:49 UTC, dtrudg commented on docs/content.go
> +  The overlay command allows to manage EXT3 writable overlay image.`
'The overlay command allows management of EXT3 writable overlay images' ?

2021-04-12 21:49 UTC, dtrudg commented on docs/content.go
> +  $ singularity overlay --size 1024 /tmp/image.sif
Needs to be `overlay create` I think

2021-04-12 21:49 UTC, dtrudg commented on docs/content.go
> +  $ singularity overlay --size 1024 /tmp/my_overlay.img`
Needs to be `overlay create` I think

2021-04-12 21:49 UTC, dtrudg commented on internal/app/singularity/overlay_create.go
> +				return fmt.Errorf("an overlay writable partition already exist in %s (ID: %d), delete it first with %q", imgPath, overlay.ID, delCmd)
```suggestion
				return fmt.Errorf("a writable overlay partition already exists in %s (ID: %d), delete it first with %q", imgPath, overlay.ID, delCmd)
```

2021-04-13 06:43 UTC, cclerget commented
Thanks for the review @dtrudg , I applied your suggestions.

>     * Why not e.g. `truncate --size 1024M myfile` instead of `dd` as that will be faster and less likely to exhaust disk as it creates a sparse file?

IIRC sparse files have been source of bugs in v2, and it doesn't apply when adding overlay in a SIF image.
Also this is the way it is done in the documentation.

> 
>     * `mkfs.ext3` is not in the standard user PATH on at least debian 10+, as that doesn't include`/sbin`. Worth looking in `/sbin` by default?

Added `setPath` which is blinldy prepending the singularity default paths to the current PATH

2021-04-13 13:25 UTC, dtrudg approved these changes
LGTM

2021-04-16 18:54 UTC, ikaneshiro approved these changes

2021-04-16 18:54 UTC, merged