Rename package github.com/sylabs/singularity to github.com/hpcng/singularity
apptainer/singularity pull request #5977
Opened 2021-05-10 20:01 UTC by cclerget

2021-05-10 20:39 UTC, DrDaveD commented on INSTALL.md
>  $ mkdir -p ${GOPATH}/src/github.com/sylabs && \
This should be  hpcng, not sylabs.

2021-05-10 20:39 UTC, DrDaveD commented on go.mod
>  go 1.13
How about the copy of golang.org/x/crypto in github.com/sylabs/golang-x-crypto, should we move that too?

2021-05-10 20:49 UTC, DrDaveD requested changes
A little more is needed in INSTALL.md, and perhaps the golang-x-crypto should be coming from hpcng.

2021-05-10 20:50 UTC, cclerget commented on INSTALL.md
>  $ mkdir -p ${GOPATH}/src/github.com/sylabs && \
fixed

2021-05-10 20:50 UTC, cclerget commented on go.mod
>  go 1.13
Yes, change applied

2021-05-10 20:52 UTC, DrDaveD approved these changes
Looks good now

2021-05-10 22:46 UTC, ikaneshiro approved these changes

2021-05-11 02:21 UTC, kmuriki approved these changes
Looks good to me. Thanks

2021-05-11 02:21 UTC, merged