Use github actions in replacement of CircleCI
apptainer/singularity pull request #5979
Opened 2021-05-10 22:54 UTC by cclerget

2021-05-11 14:57 UTC, ikaneshiro approved these changes
Lgtm

2021-05-11 18:12 UTC, DrDaveD requested changes
Please change the name of the rpmbuild build step, otherwise looks good.

2021-05-11 18:12 UTC, DrDaveD commented on .github/workflows/ci.yml
> +      - name: Set OS type and version
This step does more than set OS type and version, it actually runs the build.  That was confusing when I went to look at the output.

2021-05-11 18:12 UTC, DrDaveD commented on .github/workflows/ci.yml
> +      - name: Set OS type and version
Same here

2021-05-12 10:45 UTC, cclerget commented on .github/workflows/ci.yml
> +      - name: Set OS type and version
fixed

2021-05-12 11:49 UTC, DrDaveD approved these changes

2021-05-12 12:42 UTC, merged