Release 3.8.1 CHANGELOG and INSTALL Updates
apptainer/singularity pull request #6126
Opened 2021-08-12 18:15 UTC by kmuriki

Release 3.8.1 CHANGELOG and INSTALL file updates.

2021-08-12 20:57 UTC, DrDaveD requested changes

2021-08-12 20:57 UTC, DrDaveD commented on CHANGELOG.md
> +  - Set LABELs properly in the container when pulling from Docker/OCI source.
I believe this change is the one that was undone, not in this release.

2021-08-12 20:57 UTC, DrDaveD commented on CHANGELOG.md
> +  - `build-singularity` example pulls the base image from Docker/RockyLinux
This is too trivial, I would leave it out.

2021-08-12 20:57 UTC, DrDaveD commented on CHANGELOG.md
> +  - Partially replace the github.com/satori/go.uuid module.
This also doesn't affect anything in the behavior so it isn't needed.

2021-08-12 20:57 UTC, DrDaveD commented on CHANGELOG.md
> +### Changed defauls / behaviours
This is misspelled but the whole section is getting deleted anyway.

2021-08-12 20:57 UTC, DrDaveD commented on CHANGELOG.md
> +  - Allow escaped `\$` in a SINGULARITYENV_ var to set a literal `$` in
Also please add a note for changed functionality in #6008.  It's in some ways similar to this first note so I would put it first or second.

2021-08-12 21:02 UTC, ikaneshiro commented on internal/pkg/runtime/engine/singularity/process_linux.go
> +			// https://github.com/sylabs/singularity/issues/43
Do we want this reference in the codebase?

2021-08-12 23:16 UTC, ikaneshiro reviewed
Apologies, I missed some initially on the first pass.

2021-08-12 23:16 UTC, ikaneshiro commented on e2e/env/regressions.go
> +// https://github.com/sylabs/singularity/issues/43
And this

2021-08-12 23:50 UTC, ikaneshiro approved these changes

2021-08-13 13:21 UTC, DrDaveD commented on internal/pkg/runtime/engine/singularity/process_linux.go
> +			// https://github.com/sylabs/singularity/issues/43
I don't think it hurts, it's a valid URL that explains the issue

2021-08-13 13:24 UTC, DrDaveD approved these changes

2021-08-13 16:35 UTC, merged