Update stalebot message to close issues
apptainer/singularity pull request #6353
Opened 2022-01-18 03:02 UTC by pedroalvesbatista

## Description of the Pull Request (PR):

Updates informations, such as message and interval for stalebot to close issues.

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/hpcng/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/hpcng/singularity/blob/master/CONTRIBUTORS.md)

2022-01-24 20:03 UTC, DrDaveD commented on .github/stale.yml
> +staleLabel: close
I suggest `autoclose` instead of `close`.

2022-01-24 20:04 UTC, DrDaveD commented on .github/stale.yml
> +We appreciate your contribution and feedback.
It doesn't make sense to have this comment repeated.  Set this to `false`.

2022-01-24 20:05 UTC, DrDaveD commented on .github/stale.yml
> +   TDear user/contributor,
Typo, remove the leading `T` (and the leading blanks).

2022-01-24 20:11 UTC, DrDaveD requested changes
@kmuriki @pedroalvesbatista 

Have you gone through the issues to select the obvious ones to keep, created new issues in apptainer for them, and closed the corresponding singularity issues?  That has to be done before this is merged.

2022-01-24 21:22 UTC, pedroalvesbatista commented on .github/stale.yml
> +staleLabel: close
Got it !

2022-02-18 18:24 UTC, DrDaveD commented
The plan is for @kmuriki to instead configure [repo-lockdown](https://github.com/dessant/repo-lockdown).  Closing this.

2022-02-18 18:24 UTC, closed without merging