Add UTS namespace
apptainer/singularity pull request #911
Opened 2017-09-07 13:57 UTC by cclerget

**Description of the Pull Request (PR):**

It adds UTS namespace. After some tests to launch /sbin/init as root within an daemon instance show init (systemd) modifying "host" hostname based on container's /etc/hostname. So it could be useful and required for this use case. UTS is enabled by default even if it runs as root or normal user.

Between, make test failed on bootstrap, seems broken for all bootstrap type :

> singularity exec /tmp/stest.HRwxhl/container.img true                                       (retval=255) ERROR
> 
> ERROR  : No valid /bin/sh in container
> ABORT  : Retval = 255

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [Author's file](https://github.com/singularityware/singularity/blob/master/AUTHORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

2017-09-07 15:42 UTC, bauerm97 requested changes
Everything looks good to me, besides the copyright headers. I'm wondering if we always want to be invoking the UTS namespace or if it should only be invoked on the users request. If it should only be at user request, we should add a --uts option to the action_argparser.sh in libexec/cli/action_argparser.sh to allow the user to toggle this

2017-09-07 15:42 UTC, bauerm97 commented on src/lib/runtime/ns/uts/uts.c
> +*/
This should be changed to the new copyright header format

2017-09-07 15:42 UTC, bauerm97 commented on src/lib/runtime/ns/uts/uts.h
> +*/
As stated in the source file, this copyright header should be updated to the new version

2017-09-07 16:01 UTC, cclerget commented
This namespace is required as long container is ran as root, so maybe a conditional statement if uid == 0 ?

2017-09-26 14:06 UTC, cclerget commented
@bauerm97 up, finally enforce UTS namespace when container is run as root and add --uts option for user request

2017-10-06 09:54 UTC, cclerget commented
Close PR, I'll merge it with later

2017-10-06 09:54 UTC, closed without merging